// server/newHighsCardsGuard.js
// ── Reproducibility guard for the two New Highs backtest cards ──────────────────
// The cards (client/src/data/newHighsCards.json, generated by backtest/genNewHighsCards.mjs)
// are FROZEN engine outputs. They can only become wrong if their INPUTS change — i.e. the
// candle data they were built on gets rewritten (a split re-sync, an FMP revision, a universe
// add/remove). That is exactly the drift that put a stale +1,115% on the Carnivore card.
//
// This guard fingerprints those exact inputs. The generator stamps the fingerprint into the
// JSON when it builds it; the nightly cron recomputes the fingerprint on current data and
// ALARMS if it no longer matches — so drift trips the same day, not weeks later.
//   AI 300 card  → fingerprinted by computeInputHash (shared with treeBaselineGuard).
//   Carnivore card → fingerprintCarn (pnthr_bt_candles, the 679 store).
import crypto from 'crypto';
import fs from 'fs';
import { computeInputHash } from './treeBaselineGuard.js';

const CARDS_PATH = new URL('../client/src/data/newHighsCards.json', import.meta.url).pathname;
const CARN_END = '2026-06-11';
const CARN_MIN_BARS = 25;   // 4-week lookback (20) + 5, matches genNewHighsCards.mjs

// Canonical fingerprint of the 679 candle inputs the Carnivore backtest consumes. SHARED with
// the generator (it imports this) so the stamped hash and the checked hash can NEVER diverge.
export async function fingerprintCarn(db, end = CARN_END, minBars = CARN_MIN_BARS) {
  const docs = await db.collection('pnthr_bt_candles').find({}).toArray();
  const parts = [];
  for (const d of docs) {
    const bars = (d.daily || [])
      .filter(b => +b.low > 0 && +b.close > 0 && b.date <= end)
      .sort((a, b) => a.date.localeCompare(b.date));
    if (bars.length < minBars) continue;
    parts.push((d.ticker || '') + '|' + bars.map(b =>
      `${b.date}:${(+b.open).toFixed(4)},${(+b.high).toFixed(4)},${(+b.low).toFixed(4)},${(+b.close).toFixed(4)}`).join(';'));
  }
  parts.sort();
  return { hash: crypto.createHash('sha1').update(parts.join('\n')).digest('hex'), names: parts.length };
}

// Recompute both fingerprints, compare to the committed JSON, persist a flag, log loudly on drift.
export async function checkNewHighsCardsDrift(db) {
  let stored;
  try { stored = JSON.parse(fs.readFileSync(CARDS_PATH, 'utf8')); }
  catch (e) { console.error('[New Highs Cards Guard] cards file unreadable:', e.message); return { ok: false, error: 'unreadable' }; }

  const carn = await fingerprintCarn(db);
  const ai = await computeInputHash(db);   // same fingerprint the Tree baseline / AI card uses
  const carnDrift = stored.carn?.inputHash != null && stored.carn.inputHash !== carn.hash;
  const aiDrift = stored.ai?.inputHash != null && stored.ai.inputHash !== ai.hash;
  const drifted = carnDrift || aiDrift;
  const result = {
    drifted, carnDrift, aiDrift,
    storedCarn: stored.carn?.inputHash || null, currentCarn: carn.hash,
    storedAi: stored.ai?.inputHash || null, currentAi: ai.hash,
    checkedAt: new Date().toISOString(),
  };

  try { await db.collection('pnthr_tree_config').updateOne({}, { $set: { newHighsCardsDrift: result } }, { upsert: true }); }
  catch (e) { console.error('[New Highs Cards Guard] could not persist flag:', e.message); }

  if (drifted) {
    console.error(`🔴 [New Highs Cards Guard] DRIFT DETECTED — the New Highs backtest inputs changed (carn=${carnDrift}, ai=${aiDrift}). The cards are now STALE. Re-run: cd server/backtest && node --env-file=../.env genNewHighsCards.mjs, then commit client/src/data/newHighsCards.json.`);
  } else {
    console.log(`[New Highs Cards Guard] OK — both cards reproduce (carn ${carn.hash.slice(0, 10)} / ${carn.names} names, ai ${ai.hash.slice(0, 10)}).`);
  }
  return result;
}
