// server/treeIrService.js
// Intelligence Report data for PNTHR Tree Fund, LP — mirrors irLiveService.js
// so the same IrLivePage renders it. Reads per-tier daily NAV +
// trades from server/data/treeIr/{tier}.json (generated by backtest/genTreeIrData.js,
// which runs the SHARED treeSim engine — identical to the live dashboard baseline)
// and REUSES the exact IR math from irLiveService.js so numbers are computed identically.
//
// Backtest is HYPOTHETICAL + survivorship-flattered, frozen at go-live (2026-06-11).
// The legal mandate is long/short; the systematic implementation (and this backtest)
// is long-only 42-week-high momentum on the AI-300 universe. Not a track record.

import fs from 'fs';
import { connectToDatabase } from './database.js';
import {
  computeSide, spyMetrics, crisisAlpha, computeMarketCorrelation,
  buildSpyAnnualReturns, CRISIS_EVENTS,
} from './irLiveService.js';

const TIERS = {
  '1m':   { key: '1m',   label: 'Wagyu',       seedNav: 1000000, feeYr1to3: 20, feeYr4plus: 15 },
  '500k': { key: '500k', label: 'Porterhouse', seedNav: 500000,  feeYr1to3: 25, feeYr4plus: 20 },
  '100k': { key: '100k', label: 'Filet',       seedNav: 100000,  feeYr1to3: 30, feeYr4plus: 25 },
};

const CORR_FROM = '2023-06-01';
const _dataPath = (tier) => new URL(`./data/treeIr/${tier}.json`, import.meta.url).pathname;

const cache = {};
const CACHE_TTL = 6 * 60 * 60 * 1000;

function loadTierFile(tierKey) {
  const p = _dataPath(tierKey);
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

async function getTreeIrData(tierKey) {
  const tier = TIERS[tierKey];
  if (!tier) throw new Error(`Invalid tier: ${tierKey}`);
  if (cache[tierKey] && Date.now() - cache[tierKey].ts < CACHE_TTL) return cache[tierKey].data;

  const file = loadTierFile(tierKey);
  const grossDocs = file.grossDaily || [];
  const netDocs = file.netDaily || [];
  if (grossDocs.length === 0 || netDocs.length === 0) throw new Error(`No NAV data for tier ${tierKey}`);

  const db = await connectToDatabase();
  const [spyDoc, qqqDoc] = await Promise.all([
    db.collection('pnthr_bt_candles').findOne({ ticker: 'SPY' }),
    db.collection('pnthr_bt_candles').findOne({ ticker: 'QQQ' }),
  ]);
  const spyDaily = spyDoc?.daily || [];
  const qqqDaily = qqqDoc?.daily || [];

  const gross = computeSide(grossDocs, 'equity');
  const net = computeSide(netDocs, 'netEquity');

  // ── IR presentation policy (same as the Elite IR report): returns are NET of all fees,
  // but risk / drawdown / volatility metrics come from the STRATEGY (gross) stream so
  // quarterly performance-fee crystallization cliffs don't distort risk-adjusted quality.
  const STRATEGY_RISK_FIELDS = [
    'sharpe', 'sortino', 'maxDD', 'maxDDStart', 'maxDDTrough', 'maxDDRecovery', 'maxDDDays',
    'calmar', 'ulcerIndex', 'recoveryFactor', 'timeUnderWater',
    'positiveMonths', 'totalMonths', 'positivePct',
    'bestMonth', 'worstMonth', 'avgMonthlyReturn', 'monthlyStdDev',
    'monthlyReturns', 'top5Drawdowns', 'rolling12m', 'top10WorstDays', 'top10BestDays',
    'equityCurve',
  ];
  for (const f of STRATEGY_RISK_FIELDS) if (gross[f] !== undefined) net[f] = gross[f];
  const tradeStats = file.tradeStats || { total: 0, closed: 0, open: 0, bl: {}, ss: {}, combined: {}, combinedNet: {}, realizedDD: 0 };

  const firstTradeDate = file.firstTradeDate || gross.startDate;
  const spy = spyMetrics(spyDaily, firstTradeDate, gross.endDate, tier.seedNav, gross.startDate);

  const grossEq = grossDocs.map(d => +d.equity);
  const grossDates = grossDocs.map(d => String(d.date).slice(0, 10));
  const netEq = netDocs.map(d => +d.netEquity);
  const netDates = netDocs.map(d => String(d.date).slice(0, 10));

  const spyCorr = computeMarketCorrelation(grossDocs, spyDaily, CORR_FROM);
  const qqqCorr = computeMarketCorrelation(grossDocs, qqqDaily, CORR_FROM);

  const result = {
    tier: tier.key, label: tier.label, seedNav: tier.seedNav,
    feeSchedule: { yearsOneToThree: tier.feeYr1to3, yearsFourPlus: tier.feeYr4plus },
    gross, net, trades: tradeStats, spy, firstTradeDate,
    spyAnnualReturns: buildSpyAnnualReturns(grossDocs, spyDaily, tier.seedNav, firstTradeDate),
    crisisAlphaGross: crisisAlpha(grossEq, grossDates, spyDaily, CRISIS_EVENTS),
    crisisAlphaNet: crisisAlpha(netEq, netDates, spyDaily, CRISIS_EVENTS),
    alphaVsSpy: spy ? {
      totalReturnPts: +(net.totalReturn - spy.totalReturn).toFixed(2),
      cagrPts: +(net.cagr - spy.cagr).toFixed(2),
      endingEquityDelta: +(net.endNav - spy.endingEquity).toFixed(2),
    } : null,
    marketCorrelation: { spy: spyCorr, qqq: qqqCorr, observations: spyCorr?.observations || 0, fromDate: CORR_FROM },
    generatedAt: new Date().toISOString(),
  };

  cache[tierKey] = { data: result, ts: Date.now() };
  return result;
}

function getTreeTradeLog(tierKey) {
  const tier = TIERS[tierKey];
  if (!tier) throw new Error(`Invalid tier: ${tierKey}`);
  const file = loadTierFile(tierKey);
  const trades = (file.tradeLog || []).slice().sort((a, b) => String(a.entryDate || '').localeCompare(String(b.entryDate || '')));
  return trades.map(t => ({
    ticker: t.ticker,
    signal: t.signal,
    direction: t.direction || (t.signal === 'SS' ? 'SHORT' : 'LONG'),
    sectorName: t.sectorName || '—',
    entryDate: String(t.entryDate || '').slice(0, 10),
    exitDate: t.exitDate ? String(t.exitDate).slice(0, 10) : null,
    entryPrice: +((t.entryPrice || 0)).toFixed(2),
    exitPrice: t.exitPrice != null ? +t.exitPrice.toFixed(2) : null,
    avgCost: t.avgCost != null ? +t.avgCost.toFixed(2) : null,
    totalShares: t.totalShares || 0,
    lotsFilledCount: t.lots?.length || 1,
    totalLots: 1,
    exitReason: t.exitReason || 'ACTIVE',
    grossPnlPct: t.grossProfitPct != null ? +t.grossProfitPct.toFixed(2) : null,
    netPnlPct: t.netProfitPct != null ? +t.netProfitPct.toFixed(2) : null,
    grossPnlDollar: t.grossDollarPnl != null ? Math.round(t.grossDollarPnl) : null,
    netPnlDollar: t.netDollarPnl != null ? Math.round(t.netDollarPnl) : null,
    holdingDays: t.tradingDays || 0,
    isWinner: t.netIsWinner ?? null,
    killRank: null, tierName: null, sectorTier: null,
  }));
}

export async function treeIrMetricsHandler(req, res) {
  try {
    const data = await getTreeIrData(req.params.tier);
    res.json(data);
  } catch (err) {
    console.error('[TREE IR] Error:', err.message);
    res.status(500).json({ error: err.message });
  }
}

export async function treeIrTradesHandler(req, res) {
  try {
    const trades = getTreeTradeLog(req.params.tier);
    res.json({ trades, count: trades.length });
  } catch (err) {
    console.error('[TREE IR] Trades error:', err.message);
    res.status(500).json({ error: err.message });
  }
}
