// PNTHR AI Universe, Master holdings data with PNTHR investment-thesis paragraphs
// Each paragraph reads as: "Why PNTHR believes this name belongs in the AI Elite Universe"
// 302 holdings across 16 sectors. Last updated: 2026-05-14.
//
// v3.4 (2026-05-20): updated Index Members PDF for Multi-strategy + MCE methodology.
// v3.2 (2026-05-14): added FIX, MOD, MLI to S16 (thermal/copper), IESC to S2 (electrical infra). 298 → 302.
// v3.1 (2026-05-11): added HAWK (AI satellite intelligence) to S13 Drones, Space & Defense AI. 297 → 298.
// v3.0 (2026-05-08): removed 7 delisted/acquired tickers — ABB (delisted 2023),
//   OLO (acquired Thoma Bravo Sept 2025), ZK (acquired late 2025), IAS
//   (acquired Vista 2025), CYBR (acquired Palo Alto Networks 2026), COMM
//   (CommScope distress), CFLT (acquired Salesforce 2026). Bar data for these
//   was frozen at delisting date, producing misleading signals (e.g. ★ BL+153w
//   on ABB whose data ended 2023-06). 304 → 297 holdings, sector counts:
//   S3 -1 (COMM), S5 -2 (ABB, ZK), S7 -1 (CFLT), S8 -1 (CYBR), S9 -1 (IAS),
//   S11 -1 (OLO).
// v2.0 (2026-05-07): KRKN removed (OTC/TSXV listing only).

export const FUND_META = {
  fundName: 'PNTHR AI Universe',
  fullName: 'PNTHR AI Elite 300 Fund',
  version: 'v3.5',
  date: 'May 2026',
  totalHoldings: 304,
  totalSectors: 16,
};

export const SECTORS = [
  {
    id: 1,
    name: 'AI Compute & Semiconductors',
    weight: 29,
    thesis: 'The silicon foundation of every AI workload on Earth. From training the largest frontier models to running inference on edge devices, every AI dollar starts as a chip. PNTHR\'s largest sector concentration captures the GPUs, CPUs, custom ASICs, memory, equipment, and design tools that mint the entire AI revolution.',
    holdings: [
      { ticker: 'NVDA', name: 'NVIDIA Corporation', thesis: 'NVIDIA designs the GPUs that train and run virtually every large-scale AI model on Earth. The H100, B200, and forthcoming Rubin architectures, paired with CUDA\'s near-monopoly software moat, give NVDA pricing power no competitor has matched. Every hyperscaler, every sovereign AI program, every enterprise AI deployment funnels capital through NVIDIA. PNTHR considers NVDA the undisputed cornerstone holding of the AI Elite Universe, the picks-and-shovels of the entire AI revolution.' },
      { ticker: 'AMD', name: 'Advanced Micro Devices', thesis: 'AMD is the credible second-source challenger to NVIDIA in AI accelerators. The MI300X and MI325X have won real hyperscaler deployments at Microsoft and Meta, and ROCm software is closing the gap with CUDA every quarter. As hyperscalers structurally refuse to single-source critical AI silicon, AMD captures the natural diversification dollar. PNTHR holds AMD as the high-conviction relief-valve play to NVDA dominance.' },
      { ticker: 'AVGO', name: 'Broadcom Inc.', thesis: 'Broadcom is the silent giant of AI infrastructure. Their custom AI ASICs power Google\'s TPU program, Meta\'s MTIA accelerators, and ByteDance\'s training stacks. Combined with Tomahawk Ethernet switching silicon, the standard for AI cluster networking, Broadcom captures both compute and connectivity dollars. PNTHR holds AVGO as a foundational AI Elite name: cap-light, margin-rich, and structurally embedded in every hyperscaler\'s roadmap.' },
      { ticker: 'TSM', name: 'Taiwan Semiconductor Manufacturing', thesis: 'TSMC manufactures every leading-edge AI chip on Earth, NVIDIA H100/B200, AMD MI series, Apple Silicon, AVGO custom ASICs all run through TSMC\'s 3nm and 2nm nodes. Their CoWoS advanced packaging is THE bottleneck for AI compute supply. Without TSMC, the AI revolution stops. PNTHR holds TSM as a non-negotiable AI Elite holding, the foundry that mints every leading-edge AI dollar.' },
      { ticker: 'ARM', name: 'Arm Holdings plc', thesis: 'Arm designs the CPU architectures powering every smartphone, every NVIDIA Grace Hopper superchip, and increasingly every hyperscaler custom server. As edge AI inference and AI-PC categories explode, Arm captures royalty dollars on every chip shipped. The IP-licensing model gives Arm software-like margins on hardware-volume scale. PNTHR holds ARM as the cleanest leveraged play on AI proliferating from data centers to every device on Earth.' },
      { ticker: 'INTC', name: 'Intel Corporation', thesis: 'Intel is the deep-value, multi-year turnaround AI play. Foundry expansion, Gaudi accelerators, and Xeon\'s evolution toward AI-native CPU + accelerator architectures make INTC the only US-domiciled leading-edge fab at scale. Government CHIPS Act backing creates downside support. PNTHR holds INTC as the asymmetric optionality bet: the AI Elite Universe\'s deepest reversion candidate, with strategic geopolitical importance.' },
      { ticker: 'QCOM', name: 'Qualcomm Inc.', thesis: 'Qualcomm dominates on-device AI inference through Snapdragon platforms in smartphones, PCs, and increasingly cars. Their AI Engine and Hexagon NPU run AI workloads where the cloud can\'t reach, instant, private, low-power. As edge AI becomes the next trillion-dollar category, QCOM captures the royalty stream on every Snapdragon-powered device. PNTHR holds QCOM as the edge-AI cornerstone.' },
      { ticker: 'MRVL', name: 'Marvell Technology', thesis: 'Marvell is one of two custom-AI-silicon shops hyperscalers actually trust (alongside AVGO). Their Trainium relationship with AWS and growing Microsoft AI engagement put MRVL on every custom-ASIC bid sheet. PAM4 DSPs and electro-optics for AI clusters give them a second monetization vector. PNTHR holds MRVL as the second-derivative play on hyperscaler custom silicon, the bid that NVDA can\'t win.' },
      { ticker: 'SMCI', name: 'Super Micro Computer', thesis: 'Super Micro builds the AI server racks that NVIDIA\'s chips actually plug into. Liquid-cooled rack designs, fastest-time-to-market on new GPU generations, and direct hyperscaler relationships give SMCI an outsized share of the AI server build-out. After accounting noise reset valuations, the underlying AI demand thesis remains intact. PNTHR holds SMCI as the AI server build-out\'s purest expression.' },
      { ticker: 'MU', name: 'Micron Technology', thesis: 'Micron is the only US-domiciled HBM (high-bandwidth memory) supplier, and HBM is the second-biggest AI bottleneck after GPUs themselves. Every NVIDIA H100 and B200 needs HBM3E and HBM4. With SK Hynix and Samsung off-limits to most US investors, MU is the only HBM pure play on US exchanges. PNTHR holds MU as a foundational AI Elite holding.' },
      { ticker: 'NXPI', name: 'NXP Semiconductors', thesis: 'NXP leads automotive and edge AI silicon. AI-enabled vehicle networking, secure connectivity, and i.MX edge processors power autonomous driving stacks at every major OEM. As cars become AI computers on wheels, NXPI captures content gains per vehicle. PNTHR holds NXPI as the auto-AI silicon backbone.' },
      { ticker: 'TXN', name: 'Texas Instruments', thesis: 'Texas Instruments dominates analog and embedded AI silicon. Power management, signal conditioning, and edge inference processors from TXN sit inside virtually every AI server, robot, and connected device. Long-cycle demand and capex-heavy moat make TXN the boring-but-critical AI dollar. PNTHR holds TXN for its irreplaceable role in every AI hardware bill of materials.' },
      { ticker: 'ON', name: 'ON Semiconductor', thesis: 'ON Semiconductor leads in silicon carbide power semiconductors, the technology that makes AI data centers, EVs, and renewable grids possible at modern efficiency levels. Their Treo platform and SiC dominance position ON as a power-electronics pure play. PNTHR holds ON as a high-conviction wedge in the AI-power thesis.' },
      { ticker: 'STM', name: 'STMicroelectronics', thesis: 'STMicroelectronics designs MCUs and edge AI silicon for industrial, automotive, and IoT applications. Their SiC fab investments and AI-enabled microcontrollers make STM a European silicon-power leader. As edge AI deploys at industrial scale, STM captures embedded-compute share. PNTHR holds STM as a Europe-anchored bet on the proliferation of AI-at-the-edge.' },
      { ticker: 'ASML', name: 'ASML Holding', thesis: 'ASML is the only company on Earth that makes EUV lithography systems, the machines required to manufacture every leading-edge AI chip. There are no substitutes. There are no competitors. Every wafer flowing through TSMC, Samsung, and Intel passes through an ASML scanner. PNTHR holds ASML as a non-negotiable AI Elite holding: a global monopoly on the most critical AI manufacturing input.' },
      { ticker: 'AMAT', name: 'Applied Materials', thesis: 'Applied Materials leads the AI semiconductor equipment cycle. Every advanced node, every gate-all-around transistor, every advanced packaging step, runs through AMAT deposition, etch, and process control tools. Long-cycle equipment orders compound as AI capex extends through the decade. PNTHR holds AMAT as one of the picks-and-shovels\' picks-and-shovels.' },
      { ticker: 'KLAC', name: 'KLA Corporation', thesis: 'KLA owns process control and metrology in advanced semiconductor manufacturing. As AI chips push to 2nm and 3D packaging gets more complex, every wafer needs more KLA inspection. Margin profile, oligopoly position, and long capex cycle make KLAC a quality-compounder AI play. PNTHR holds KLAC as the highest-margin pure semi-equipment exposure.' },
      { ticker: 'LRCX', name: 'Lam Research', thesis: 'Lam Research dominates etch and deposition for memory and advanced logic. HBM stacking, 3D NAND scaling, and gate-all-around transistors all flow through LRCX equipment. Memory cycle plus AI capex creates a dual tailwind. PNTHR holds LRCX as the etch/deposition pure play in our AI Elite semi-equipment basket.' },
      { ticker: 'TER', name: 'Teradyne', thesis: 'Teradyne builds the test equipment that every AI chip must pass before shipment. As AI chip complexity explodes, test time per die rises, a structural revenue tailwind. Their robotics arm captures the autonomy/manufacturing-AI cross-trade. PNTHR holds TER for its dual exposure to AI semi test and warehouse robotics.' },
      { ticker: 'CAMT', name: 'Camtek Ltd', thesis: 'Camtek delivers metrology and inspection systems specifically for advanced packaging, the AI manufacturing bottleneck. As CoWoS, hybrid bonding, and chiplet integration become standard, CAMT\'s equipment becomes mandatory. Small-cap leverage to advanced packaging makes CAMT one of the highest-beta AI-equipment exposures. PNTHR holds CAMT as a focused advanced-packaging pure play.' },
      { ticker: 'ACLS', name: 'Axcelis Technologies', thesis: 'Axcelis builds ion implantation systems for memory and power semiconductor manufacturing. SiC power semis and HBM memory both need Axcelis. As AI data centers drive memory and power-silicon capex, ACLS captures the trade. PNTHR holds ACLS as a focused leveraged play on the SiC + memory tailwinds.' },
      { ticker: 'MKSI', name: 'MKS Instruments', thesis: 'MKS Instruments supplies the precision motion, vacuum, and measurement subsystems inside every wafer fab and AI manufacturing line. As advanced packaging and AI chip complexity scale, MKS\'s content per tool grows. PNTHR holds MKSI for its diversified, often-overlooked exposure to every leg of AI semi capex.' },
      { ticker: 'CDNS', name: 'Cadence Design Systems', thesis: 'Cadence makes the EDA software that designs every AI chip on Earth. Without Cadence, no NVIDIA H100, no AVGO TPU, no AMD MI300. As AI chip complexity explodes, software seat counts and revenue per design rise structurally. PNTHR holds CDNS as a pure, recurring-revenue, software-margin AI design play, the picks-and-shovels at the digital frontier.' },
      { ticker: 'SNPS', name: 'Synopsys', thesis: 'Synopsys is Cadence\'s duopoly partner in EDA, the other indispensable AI chip design software vendor. Their Ansys acquisition extends them into multiphysics simulation for AI chip thermal and electrical design. Two vendors, infinite chip complexity ahead. PNTHR holds SNPS as the second leg of our EDA duopoly trade.' },
      { ticker: 'IPGP', name: 'IPG Photonics', thesis: 'IPG Photonics makes the high-power lasers enabling advanced AI chip lithography processes, hybrid bonding, and EV battery manufacturing. Vertical fiber-laser integration gives IPG cost and capability advantages no peer matches. PNTHR holds IPGP as a focused photonics pure play with multi-AI-vector exposure.' },
      { ticker: 'LASR', name: 'nLIGHT Inc.', thesis: 'nLIGHT supplies high-power semiconductor lasers for advanced manufacturing, defense directed-energy, and additive manufacturing, all AI-adjacent end markets. Defense-AI directed energy is an emerging revenue lever. PNTHR holds LASR as a small-cap photonics + defense-AI hybrid bet.' },
      { ticker: 'DELL', name: 'Dell Technologies', thesis: 'Dell is the #1 reseller of NVIDIA HGX and DGX AI server systems. Massive AI revenue, direct hyperscaler relationships, and unmatched supply-chain scale make DELL the single largest channel for NVIDIA\'s AI silicon to actually reach customers. PNTHR holds DELL as a top-tier AI Elite holding, the channel through which AI compute is sold.' },
      { ticker: 'HPE', name: 'Hewlett Packard Enterprise', thesis: 'HPE sells AI servers, networking (Aruba), and supercomputing (Cray) as a one-stop AI infrastructure vendor. Their Juniper acquisition cements their networking platform. Government and Department of Defense AI contracts add a defense-AI angle. PNTHR holds HPE as DELL\'s complementary AI server peer in our basket.' },
      { ticker: 'CLS', name: 'Celestica Inc.', thesis: 'Celestica designs and assembles AI servers, switches, and storage systems on contract for hyperscalers. AI demand has reset their growth trajectory and the multiple. As neoclouds and hyperscalers want fewer name-brand servers and more custom builds, CLS gets the call. PNTHR holds CLS as the contract-manufacturing pure play on AI server scale.' },
      { ticker: 'FLEX', name: 'Flex Ltd', thesis: 'Flex manufactures custom AI infrastructure at scale for hyperscalers and OEMs. Their AI server, power, and cooling integration capability makes them an essential partner for the AI buildout. PNTHR holds FLEX as a margin-expanding contract manufacturer riding the AI capex wave.' },
      { ticker: 'JBL', name: 'Jabil Inc.', thesis: 'Jabil is Flex\'s contract-manufacturing peer with similar AI-server exposure across hyperscaler builds, networking, and power. Cap-light model with structural AI tailwinds makes JBL a cleaner AI Elite holding than its diversified industrial appearance suggests. PNTHR holds JBL as the second leg of our contract-manufacturing AI bet.' },
      { ticker: 'OLED', name: 'Universal Display Corp', thesis: 'Universal Display owns the foundational IP for OLED display technology, the screens on every AI-enabled smartphone, laptop, and AR/VR device. As AI personal devices proliferate, OLED collects royalty dollars on each unit. PNTHR holds OLED as a unique IP-licensing AI-device play.' },
      { ticker: 'WDC', name: 'Western Digital', thesis: 'Western Digital, post-spinoff, is the pure-play HDD vendor, and AI training data lakes need HDDs at massive scale. As AI datasets explode, hyperscaler HDD demand inflects. PNTHR holds WDC for its unique exposure to AI\'s storage backbone.' },
      { ticker: 'SNDK', name: 'SanDisk Corporation', thesis: 'SanDisk, the pure-play NAND flash spinoff from Western Digital, captures the AI training data plus AI device flash storage trade with no HDD dilution. AI training stores petabytes of data; SNDK supplies the high-density NAND. PNTHR holds SNDK as a recently-public, focused NAND pure play with AI-storage tailwinds.' },
      { ticker: 'PSTG', name: 'Pure Storage', thesis: 'Pure Storage owns AI-flash storage for training clusters. Hyperscalers and Fortune 500 enterprises buy Pure\'s all-flash arrays to feed AI training jobs at maximum throughput. Their storage-as-a-service model creates recurring revenue. PNTHR holds PSTG as the leading AI-flash storage pure play.' },
      { ticker: 'STX', name: 'Seagate Technology', thesis: 'Seagate is the second leg of the HDD-for-AI trade. Mass-data AI training is HDD-bound for raw cost reasons; Seagate\'s mass-capacity drives capture the dollar. AI hyperscaler exabyte demand creates multi-year HDD cycle. PNTHR holds STX as the pure HDD-for-AI play.' },
      { ticker: 'NTAP', name: 'NetApp Inc.', thesis: 'NetApp delivers hybrid-cloud AI storage software running across AWS, Azure, GCP, and on-prem. Their AIPod with NVIDIA partnership puts NetApp inside enterprise AI data pipelines. PNTHR holds NTAP as the software-defined AI-storage play complementing the hardware names.' },
      { ticker: 'MPWR', name: 'Monolithic Power Systems', thesis: 'Monolithic Power supplies power management semiconductors specifically engineered for AI server boards. Every NVIDIA HGX baseboard runs MPWR silicon. AI-server power density is exploding, and MPWR\'s content per server rises with it. PNTHR considers MPWR one of the most under-owned AI Elite holdings, the silicon inside the silicon.' },
      { ticker: 'ENTG', name: 'Entegris Inc.', thesis: 'Entegris supplies advanced materials, gas filters, and chemicals to TSMC, Intel, and Samsung for leading-edge AI chip manufacturing. Higher node complexity equals higher Entegris content per wafer. PNTHR holds ENTG as a deep-moat materials pure play on the AI manufacturing super-cycle.' },
      { ticker: 'WOLF', name: 'Wolfspeed Inc.', thesis: 'Wolfspeed is the pure-play silicon carbide power semiconductor leader. SiC is THE next-gen power electronics technology for AI data centers, EVs, and grid infrastructure. Beaten down on capacity-ramp execution, WOLF still commands the SiC moat. PNTHR holds WOLF as a high-beta deep-value AI-power option.' },
      { ticker: 'NVTS', name: 'Navitas Semiconductor', thesis: 'Navitas designs gallium nitride and silicon carbide power chips for AI data centers, EV chargers, and renewable infrastructure. GaN-based AI server power supplies dramatically improve efficiency. PNTHR holds NVTS as a small-cap power-AI specialist.' },
      { ticker: 'AMBA', name: 'Ambarella Inc.', thesis: 'Ambarella designs edge-AI vision systems-on-chip, the silicon brains in autonomous cars, robots, drones, and smart cameras. As edge AI displaces cloud inference for cost and latency reasons, AMBA captures the trade. PNTHR holds AMBA as a focused edge-vision AI pure play.' },
      { ticker: 'LSCC', name: 'Lattice Semiconductor', thesis: 'Lattice is the leader in low-power FPGAs, the reconfigurable silicon increasingly used for AI edge inference, networking, and security. Their AI-friendly architectures and low power profile drive design wins. PNTHR holds LSCC as a small-cap acquisition target with edge-AI growth optionality.' },
      { ticker: 'ONTO', name: 'Onto Innovation', thesis: 'Onto Innovation supplies advanced metrology and inspection equipment for advanced packaging, the CoWoS bottleneck of AI compute. As 2.5D and 3D chiplet integration scales, ONTO\'s tools become mandatory. PNTHR holds ONTO as a small-cap pure play on advanced packaging, the AI manufacturing chokepoint.' },
      { ticker: 'CBRS', name: 'Cerebras Systems', thesis: 'Cerebras builds the largest AI chips ever made, wafer-scale engines purpose-built for training and inference of frontier AI models. Their CS-3 system eliminates memory-bandwidth bottlenecks that constrain traditional GPU clusters, delivering order-of-magnitude speedups on large language models. As enterprises and sovereign AI programs seek alternatives to NVIDIA for training economics, Cerebras captures the custom-silicon dollar. PNTHR holds CRBS as a pure-play AI training accelerator with wafer-scale differentiation no competitor can replicate.' },
      { ticker: 'KLIC', name: 'Kulicke & Soffa', thesis: 'Kulicke & Soffa makes the wire bonders and advanced packaging equipment that assemble HBM stacks and AI chiplets. As HBM4 and hybrid bonding ramp, K&S captures the equipment dollar. PNTHR holds KLIC as a focused AI-packaging equipment specialist.' },
      { ticker: 'FORM', name: 'FormFactor Inc.', thesis: 'FormFactor designs probe cards used to test every advanced AI chip before shipment. Higher chip complexity equals higher probe card content. Their HBM and advanced-logic test card franchises capture AI dollars. PNTHR holds FORM as a niche, high-margin AI test specialist.' },
      { ticker: 'KEYS', name: 'Keysight Technologies', thesis: 'Keysight builds the test, measurement, and validation systems for AI networks, AI chips, and 5G/6G infrastructure. As AI cluster speeds push 800G to 1.6T, Keysight\'s test platforms become essential. PNTHR holds KEYS as the diversified high-quality AI test and measurement leader.' },
      { ticker: 'AEHR', name: 'Aehr Test Systems', thesis: 'Aehr Test is a small-cap pure play on test and burn-in for SiC power semis and high-density AI memory. As SiC and HBM scale, Aehr\'s customer concentration becomes a feature, not a bug. PNTHR holds AEHR as a high-beta lottery-ticket bet on the SiC plus memory boom.' },
      { ticker: 'SITM', name: 'SiTime Corporation', thesis: 'SiTime designs MEMS-based precision timing chips, the silicon clocks that synchronize AI cluster networking, 5G base stations, and aerospace systems. Their displacement of legacy quartz crystals captures content share in every AI data center. PNTHR holds SITM as a uniquely positioned AI-timing pure play.' },
      { ticker: 'PI', name: 'Impinj Inc.', thesis: 'Impinj leads RAIN RFID, the IoT and edge-AI tagging technology. As physical-AI applications (warehouse robots, retail tracking) scale, RAIN RFID becomes infrastructure. PNTHR holds PI as an edge-IoT pure play with AI-physical-world thesis.' },
      { ticker: 'MXL', name: 'MaxLinear Inc.', thesis: 'MaxLinear designs connectivity and broadband chips for AI data centers, fiber optics, and 5G. Their AI infrastructure chip portfolio captures the bandwidth-bottleneck trade. PNTHR holds MXL as a focused small-cap AI connectivity play.' },
    ],
  },
  {
    id: 2,
    name: 'AI Power, Energy & Electrification',
    weight: 17,
    thesis: 'AI is the largest electrical load growth event in modern grid history. Hyperscalers are signing direct power deals, nuclear, gas, renewable, because the existing grid cannot meet AI training demand. PNTHR\'s second-largest sector captures the utilities, nuclear operators, gas producers, electrical equipment, and storage companies that will literally power the AI revolution.',
    holdings: [
      { ticker: 'GEV', name: 'GE Vernova', thesis: 'GE Vernova builds the gas turbines, wind turbines, and grid-scale electrical equipment powering the AI infrastructure buildout. Their HA-class gas turbines are the workhorse of new gas-fired AI data centers, with multi-year backlogs. PNTHR holds GEV as a foundational AI-power Elite holding, the company that builds the actual generation capacity AI needs.' },
      { ticker: 'CEG', name: 'Constellation Energy', thesis: 'Constellation operates the largest US nuclear fleet and signed the landmark Three Mile Island restart deal with Microsoft to power AI data centers. Nuclear is THE preferred AI baseload, clean, reliable, 24/7. CEG captures the premium pricing for this exact use case. PNTHR considers CEG the cornerstone AI-nuclear holding.' },
      { ticker: 'VST', name: 'Vistra Corp.', thesis: 'Vistra owns nuclear and gas generation directly serving hyperscaler AI data center demand, including the Comanche Peak AI deal. Their Texas and Pennsylvania assets sit precisely where AI compute is being built. PNTHR holds VST as a top-tier AI-power play with both nuclear baseload and gas peaker exposure.' },
      { ticker: 'TLN', name: 'Talen Energy', thesis: 'Talen owns Susquehanna nuclear plant, the AI power deal with Amazon Web Services that catalyzed the entire nuclear-for-AI thesis. Pure-play nuclear behind the meter for AWS. PNTHR holds TLN as a focused nuclear-AI pure play.' },
      { ticker: 'NEE', name: 'NextEra Energy', thesis: 'NextEra is the largest US utility with the most renewable + storage capacity, supplying clean power to hyperscaler AI data centers. Their Florida + national renewables footprint, plus regulated utility cash flows, give NEE a uniquely defensive AI-power profile. PNTHR holds NEE as the diversified utility leg of our AI-power basket.' },
      { ticker: 'SRE', name: 'Sempra Energy', thesis: 'Sempra operates Texas and California utility assets plus LNG export, both of which serve AI data center demand. Texas data center power buildout sits squarely on Sempra\'s grid. PNTHR holds SRE as a regulated-utility AI play with LNG optionality.' },
      { ticker: 'CWEN', name: 'Clearway Energy', thesis: 'Clearway owns renewable + storage assets supplying AI-grade clean power under long-term contracts. Hyperscaler clean energy mandates create structural demand. PNTHR holds CWEN as a yield-and-growth AI-renewables play.' },
      { ticker: 'AES', name: 'AES Corporation', thesis: 'AES has signed direct AI data center power deals (including Amazon and Google) and operates a global renewable + storage platform. Their AI-tailwind power contracts are reaccelerating growth. PNTHR holds AES as a re-rating utility with explicit hyperscaler exposure.' },
      { ticker: 'CCJ', name: 'Cameco Corporation', thesis: 'Cameco is the largest publicly traded uranium producer and owns 49% of Westinghouse, the reactor builder. As nuclear becomes THE AI power solution, uranium demand and Westinghouse revenues both inflect. PNTHR holds CCJ as a foundational AI-nuclear fuel and equipment Elite holding.' },
      { ticker: 'OKLO', name: 'Oklo Inc.', thesis: 'Oklo is the leading small modular reactor pure-play, backed by Sam Altman, designed specifically for behind-the-meter AI data center power. First commercial deployments create explosive optionality. PNTHR holds OKLO as a high-beta AI-nuclear lottery ticket with massive upside if SMR technology scales.' },
      { ticker: 'BE', name: 'Bloom Energy', thesis: 'Bloom Energy builds solid-oxide fuel cells deployed behind-the-meter at AI data centers for instant on-site power generation. Hyperscaler announcements have catalyzed re-rating. PNTHR holds BE as a unique fuel-cell AI-power exposure.' },
      { ticker: 'SMR', name: 'NuScale Power', thesis: 'NuScale is the only SMR with NRC design certification, first-mover in the small modular reactor revolution. As AI power demand outstrips conventional grid expansion, SMRs become essential. PNTHR holds SMR as the highest-conviction SMR pure play.' },
      { ticker: 'NNE', name: 'Nano Nuclear Energy', thesis: 'Nano Nuclear develops portable micro-reactors for distributed AI data center power, defense bases, and remote industrial sites. Speculative but uniquely positioned. PNTHR holds NNE as a small-cap micro-reactor lottery ticket in our AI-nuclear book.' },
      { ticker: 'ETN', name: 'Eaton Corporation', thesis: 'Eaton builds the electrical distribution, switchgear, and power management systems that connect generation to AI data center racks. Their content-per-data-center is exploding. PNTHR holds ETN as a top-tier AI electrical infrastructure Elite holding.' },
      { ticker: 'PWR', name: 'Quanta Services', thesis: 'Quanta is the largest US electrical infrastructure construction firm, they build the transmission lines and substations connecting power plants to AI data centers. Multi-year backlogs reflect AI grid buildout. PNTHR holds PWR as the construction services leg of our AI-power thesis.' },
      { ticker: 'D', name: 'Dominion Energy', thesis: 'Dominion is the regulated utility serving Virginia\'s "Data Center Alley", the world\'s largest concentration of AI data centers. They are literally THE utility for AI compute capacity in North America. PNTHR considers D a non-negotiable AI-power Elite holding.' },
      { ticker: 'HUBB', name: 'Hubbell Incorporated', thesis: 'Hubbell makes the electrical components, connectors, and grid hardware AI data centers need at scale. Hyperscaler buildouts directly drive Hubbell volumes. PNTHR holds HUBB as a quietly compounding AI electrical equipment play.' },
      { ticker: 'GNRC', name: 'Generac Holdings', thesis: 'Generac builds the backup power generators that AI data centers and critical facilities require. Hyperscaler resiliency mandates plus C&I demand drive growth. PNTHR holds GNRC as a focused AI-resilience power play.' },
      { ticker: 'POWL', name: 'Powell Industries', thesis: 'Powell Industries manufactures custom-engineered switchgear and electrical equipment for AI data centers, LNG export terminals, and oil and gas. Massive AI-driven backlog reset valuation. PNTHR holds POWL as a small-cap, high-conviction AI electrical equipment specialist.' },
      { ticker: 'STRL', name: 'Sterling Infrastructure', thesis: 'Sterling builds the data center site preparation and infrastructure work, the actual physical AI data center buildout. Direct AI capex tailwind. PNTHR holds STRL as a focused AI data center construction pure play.' },
      { ticker: 'MTZ', name: 'MasTec Inc.', thesis: 'MasTec constructs power transmission, oil and gas pipelines, and clean energy infrastructure, including transmission for AI data center power. PNTHR holds MTZ as a diversified construction services play on the AI grid buildout.' },
      { ticker: 'PRIM', name: 'Primoris Services', thesis: 'Primoris builds power transmission, gas pipelines, and industrial infrastructure connecting AI data centers to generation. Backlog reflects AI capex. PNTHR holds PRIM as a focused energy-and-power construction services AI play.' },
      { ticker: 'CMI', name: 'Cummins Inc.', thesis: 'Cummins makes the power generation systems, diesel and gas gensets, providing backup and prime power to AI data centers. Hyperscaler gen-set demand is reaccelerating. PNTHR holds CMI as a quality industrial with explicit AI data center exposure.' },
      { ticker: 'WCC', name: 'WESCO International', thesis: 'WESCO is the largest electrical equipment distributor serving AI data center buildouts, electrical contractors, and industrial AI deployments. AI capex flows through their warehouses. PNTHR holds WCC as the distribution channel leg of our AI electrical thesis.' },
      { ticker: 'ENPH', name: 'Enphase Energy', thesis: 'Enphase leads in AI-managed solar microinverters and battery storage. Their software optimizes home + commercial energy across the grid. PNTHR holds ENPH as a software-margin renewables-AI play.' },
      { ticker: 'FLNC', name: 'Fluence Energy', thesis: 'Fluence is the leading utility-scale battery energy storage system integrator. AI-managed grid storage is critical infrastructure for renewable AI power. PNTHR holds FLNC as a focused grid-scale storage pure play.' },
      { ticker: 'STEM', name: 'Stem Inc.', thesis: 'Stem provides AI-driven energy storage software for commercial and industrial grid optimization. Pure-play AI energy software with deep moat. PNTHR holds STEM as a small-cap AI-grid software bet.' },
      { ticker: 'PLUG', name: 'Plug Power', thesis: 'Plug Power develops hydrogen fuel cell systems for industrial, mobility, and stationary power. Hydrogen could become a clean baseload solution for AI data centers. PNTHR holds PLUG as a speculative hydrogen-AI power option.' },
      { ticker: 'EVGO', name: 'EVgo Inc.', thesis: 'EVgo operates fast-charging EV networks managed by AI optimization software. As autonomous EV fleets scale, EVgo benefits. PNTHR holds EVGO for EV-charging-network exposure within the AI-power book.' },
      { ticker: 'CHPT', name: 'ChargePoint Holdings', thesis: 'ChargePoint runs the largest EV charging network globally with AI-driven utilization software. Long-term EV transition tailwind. PNTHR holds CHPT as the second leg of our EV-charging exposure.' },
      { ticker: 'BLNK', name: 'Blink Charging', thesis: 'Blink builds and operates EV charging stations across the US and Europe. High-beta small-cap EV-charging exposure. PNTHR holds BLNK as a small-cap optionality bet within our EV-AI charging book.' },
      { ticker: 'EQT', name: 'EQT Corporation', thesis: 'EQT is the #1 Appalachian natural gas producer, directly supplying the gas-fired AI data centers being built across Pennsylvania, Ohio, and Virginia. AI gas demand is THE under-discussed bull case. PNTHR holds EQT as a non-negotiable AI-gas pure play.' },
      { ticker: 'KMI', name: 'Kinder Morgan', thesis: 'Kinder Morgan operates the largest US natural gas pipeline network, already announcing multiple AI data center direct supply deals. As AI runs on gas, KMI runs the gas. PNTHR holds KMI as the cornerstone AI-pipeline holding.' },
      { ticker: 'WMB', name: 'Williams Companies', thesis: 'Williams operates the Transco interstate gas pipeline serving the eastern AI data center corridor. Long-term contracts with AI-driven gas demand growth. PNTHR holds WMB as the second leg of our AI-pipeline trade.' },
      { ticker: 'TRGP', name: 'Targa Resources', thesis: 'Targa is the leading Permian midstream gas processor, moving the gas that powers Texas AI data centers and LNG exports. PNTHR holds TRGP as a focused Permian midstream AI-gas play.' },
      { ticker: 'OKE', name: 'ONEOK Inc.', thesis: 'ONEOK operates major gas gathering and pipeline assets across the Mid-Continent and Permian, increasingly supplying AI data center demand. PNTHR holds OKE as a diversified midstream AI-gas play.' },
      { ticker: 'LNG', name: 'Cheniere Energy', thesis: 'Cheniere is the largest US LNG exporter, energy security and AI-driven gas demand both flow through their terminals. PNTHR holds LNG as the LNG-export leg of our AI energy security thesis.' },
      { ticker: 'IESC', name: 'IES Holdings', thesis: 'IES Holdings is a leading electrical and technology systems contractor building critical power infrastructure for AI data centers. Their communications and infrastructure segments directly serve hyperscaler electrical buildouts. PNTHR holds IESC as a focused electrical contracting pure play on AI data center construction.' },
    ],
  },
  {
    id: 3,
    name: 'AI Optical, Photonics & Networking',
    weight: 13,
    thesis: 'AI clusters move oceans of data between GPUs at speeds that only optical can deliver. The bandwidth bottleneck of AI training has minted a new generation of optical and networking leaders. PNTHR\'s third-largest sector captures the silent winners of the AI bandwidth wars, names like CRDO and ALAB that the broader market is still under-owning.',
    holdings: [
      { ticker: 'ANET', name: 'Arista Networks', thesis: 'Arista is the leader in high-speed Ethernet switching for AI data centers. Their 800G platforms ship into every major hyperscaler AI cluster, displacing InfiniBand. PNTHR holds ANET as a top-tier AI networking Elite holding, bandwidth bottleneck monetized.' },
      { ticker: 'CSCO', name: 'Cisco Systems', thesis: 'Cisco is the legacy networking giant adding AI-native switching, security, and observability through their Splunk acquisition. AI data center networking refresh creates re-rating optionality. PNTHR holds CSCO as the diversified mega-cap AI networking play.' },
      { ticker: 'COHR', name: 'Coherent Corp', thesis: 'Coherent is a leading optical components and laser supplier, they make the transceivers, lasers, and optics inside every AI data center optical link. PNTHR holds COHR as a focused AI-optical pure play.' },
      { ticker: 'LITE', name: 'Lumentum Holdings', thesis: 'Lumentum supplies high-speed optical components for AI data center interconnects and 3D sensing. AI bandwidth scaling is the structural revenue tailwind. PNTHR holds LITE as a top-tier AI photonics name.' },
      { ticker: 'FN', name: 'Fabrinet', thesis: 'Fabrinet is the contract manufacturer building optical transceivers and modules for NVIDIA, AVGO, and the entire AI optical supply chain. Pure-play AI bandwidth manufacturing. PNTHR holds FN as a focused AI optical manufacturing pure play.' },
      { ticker: 'CRDO', name: 'Credo Technology', thesis: 'Credo makes the high-speed SerDes, AECs, and optical DSP chips powering 800G and 1.6T AI cluster interconnects. AI cluster scale-out is THE Credo demand thesis. PNTHR holds CRDO as a high-conviction small-cap AI optical pure play and one of our most under-owned alpha names.' },
      { ticker: 'ALAB', name: 'Astera Labs', thesis: 'Astera Labs provides PCIe and CXL connectivity silicon enabling AI server and rack-scale architectures. Direct beneficiary of NVIDIA HGX and B200 ramp. PNTHR holds ALAB as a top-tier AI-connectivity Elite holding.' },
      { ticker: 'AAOI', name: 'Applied Optoelectronics', thesis: 'Applied Optoelectronics manufactures optical transceivers for AI data center interconnects and broadband. Pure AI bandwidth pure play with leveraged exposure. PNTHR holds AAOI as a high-beta AI optical small cap.' },
      { ticker: 'MTSI', name: 'MACOM Technology', thesis: 'MACOM designs analog and photonic semiconductors for AI optical networks, defense radar, and 5G. Diversified AI photonics exposure. PNTHR holds MTSI as a focused photonics-and-RF AI play.' },
      { ticker: 'CIEN', name: 'Ciena Corporation', thesis: 'Ciena builds the long-haul optical networking systems connecting AI data centers across continents. AI bandwidth growth is structural. PNTHR holds CIEN as the long-haul optical AI play.' },
      { ticker: 'VIAV', name: 'Viavi Solutions', thesis: 'Viavi provides network test and assurance plus optical filters for AI data centers and 5G. PNTHR holds VIAV as a diversified optical test AI play.' },
      { ticker: 'GLW', name: 'Corning Inc.', thesis: 'Corning manufactures the optical fiber that connects every AI data center and the cover glass on AI-enabled devices. Multi-vector AI exposure. PNTHR holds GLW as a foundational AI materials Elite holding.' },
      { ticker: 'APH', name: 'Amphenol Corporation', thesis: 'Amphenol designs the high-speed connectors inside AI servers, networking gear, and EVs. Content per AI server is exploding. PNTHR holds APH as a top-tier AI connectivity Elite name.' },
      { ticker: 'TEL', name: 'TE Connectivity', thesis: 'TE Connectivity is Amphenol\'s peer in connectors and sensors for AI servers, EVs, and industrial automation. PNTHR holds TEL as the second leg of our AI-connector duopoly trade.' },
      { ticker: 'VICR', name: 'Vicor Corporation', thesis: 'Vicor makes power-on-package modules powering NVIDIA Grace Hopper and AI server boards. Highest-density AI power conversion. PNTHR holds VICR as a focused AI power-conversion small cap.' },
      { ticker: 'POET', name: 'POET Technologies', thesis: 'POET Technologies pioneers integrated silicon photonics for AI data center transceivers. Speculative but uniquely positioned in next-gen optical. PNTHR holds POET as a small-cap silicon photonics lottery ticket.' },
      { ticker: 'FFIV', name: 'F5 Inc.', thesis: 'F5 secures and accelerates AI application traffic across enterprise and cloud networks. AI inference workloads need F5. PNTHR holds FFIV as the application-layer AI networking play.' },
    ],
  },
  {
    id: 4,
    name: 'AI Cloud, Data Centers & Edge',
    weight: 7,
    thesis: 'AI compute lives somewhere, and that "somewhere" is increasingly purpose-built AI data centers, neoclouds, and edge nodes. PNTHR captures the REITs that own AI real estate, the neoclouds that rent GPU capacity, the Bitcoin miners pivoting to AI hosting, and the edge networks delivering AI to end users.',
    holdings: [
      { ticker: 'EQIX', name: 'Equinix Inc.', thesis: 'Equinix operates the largest network of carrier-neutral data centers, the interconnection hubs where AI workloads meet the internet. Foundational AI data center REIT. PNTHR holds EQIX as the cornerstone AI real estate Elite holding.' },
      { ticker: 'DLR', name: 'Digital Realty Trust', thesis: 'Digital Realty is the largest pure-play data center REIT with massive hyperscaler AI tenant exposure. AI capacity demand drives multi-year leasing tailwind. PNTHR holds DLR as a top-tier AI data center REIT.' },
      { ticker: 'IRM', name: 'Iron Mountain', thesis: 'Iron Mountain runs a fast-growing data center business alongside their data and records storage business. AI data growth lifts both. PNTHR holds IRM as a diversified AI-data-storage REIT play.' },
      { ticker: 'CRWV', name: 'CoreWeave Inc.', thesis: 'CoreWeave is the pure-play AI GPU cloud, the original "neocloud." Recently public, deeply tied to NVIDIA and Microsoft, structurally short GPU capacity. PNTHR holds CRWV as the highest-profile AI neocloud pure play.' },
      { ticker: 'NBIS', name: 'Nebius Group', thesis: 'Nebius operates AI-optimized cloud infrastructure with European AI exposure. Yandex spinoff repositioned as AI compute pure play. PNTHR holds NBIS as a focused European AI neocloud bet.' },
      { ticker: 'IREN', name: 'IREN Limited', thesis: 'IREN operates Bitcoin mining capacity transitioning to AI hosting at sustainable energy sites in Texas and British Columbia. PNTHR holds IREN as a Bitcoin-to-AI-pivot pure play.' },
      { ticker: 'APLD', name: 'Applied Digital', thesis: 'Applied Digital is the original Bitcoin-to-AI hosting pivot, pure-play AI GPU hosting facility operator. PNTHR holds APLD as a high-beta AI hosting pure play.' },
      { ticker: 'CORZ', name: 'Core Scientific', thesis: 'Core Scientific operates massive Bitcoin mining capacity now hosting CoreWeave\'s AI GPUs at scale. Direct AI infrastructure exposure with Bitcoin optionality. PNTHR holds CORZ as a top-tier Bitcoin-to-AI hosting pivot.' },
      { ticker: 'WULF', name: 'TeraWulf', thesis: 'TeraWulf operates the Lake Mariner facility transitioning Bitcoin capacity to AI hosting. Pure-play sustainable energy AI hosting. PNTHR holds WULF as a small-cap Bitcoin-AI pivot.' },
      { ticker: 'MARA', name: 'Marathon Digital Holdings', thesis: 'MARA is the largest US Bitcoin miner increasingly evaluating AI hosting opportunities at their power-rich sites. PNTHR holds MARA as Bitcoin-with-AI-optionality.' },
      { ticker: 'HUT', name: 'Hut 8 Mining', thesis: 'Hut 8 operates Bitcoin mining and high-performance computing infrastructure at multiple Texas and Alberta sites. PNTHR holds HUT as Bitcoin-AI hybrid exposure.' },
      { ticker: 'CIFR', name: 'Cipher Mining', thesis: 'Cipher Mining operates Texas-based Bitcoin mining capacity with explicit AI hosting pivot strategy. PNTHR holds CIFR as a small-cap Bitcoin-AI conversion bet.' },
      { ticker: 'HIVE', name: 'HIVE Digital Technologies', thesis: 'HIVE Digital operates green-energy Bitcoin mining and AI compute infrastructure across Canada, Sweden, and Iceland. PNTHR holds HIVE as a green-energy Bitcoin-AI pivot.' },
      { ticker: 'BITF', name: 'Bitfarms', thesis: 'Bitfarms operates Bitcoin mining facilities increasingly evaluating AI hosting. PNTHR holds BITF as small-cap Bitcoin-AI optionality.' },
      { ticker: 'NET', name: 'Cloudflare Inc.', thesis: 'Cloudflare is the leading edge AI compute platform, Workers AI runs inference at the network edge globally. Edge inference is a structural AI growth vector. PNTHR holds NET as the cornerstone edge-AI platform.' },
      { ticker: 'NTNX', name: 'Nutanix Inc.', thesis: 'Nutanix delivers hybrid cloud infrastructure software for enterprise AI workloads. Their NVIDIA partnership puts them inside enterprise AI deployment. PNTHR holds NTNX as an enterprise hybrid-cloud AI play.' },
      { ticker: 'AKAM', name: 'Akamai Technologies', thesis: 'Akamai is repositioning from CDN to edge AI compute and security. Distributed AI inference is the future. PNTHR holds AKAM as an edge-AI evolution play.' },
      { ticker: 'AMT', name: 'American Tower', thesis: 'American Tower owns the cell towers and edge data center sites where 5G + AI inference will be deployed. Structural AI edge tailwind. PNTHR holds AMT as a tower REIT with AI-edge optionality.' },
      { ticker: 'CCI', name: 'Crown Castle', thesis: 'Crown Castle owns US towers and fiber networks supporting 5G and edge AI. PNTHR holds CCI as the second leg of our tower-REIT AI-edge book.' },
    ],
  },
  {
    id: 5,
    name: 'Robotics, Autonomous & Auto AI',
    weight: 6,
    thesis: 'AI is breaking out of data centers and into the physical world, robots, autonomous cars, autonomous trucks, drones, eVTOLs. PNTHR captures the leaders making AI-first hardware that moves: industrial robots, surgical robots, autonomous driving, LIDAR, and the Tier 1 suppliers that integrate AI into vehicles.',
    holdings: [
      { ticker: 'TSLA', name: 'Tesla Inc.', thesis: 'Tesla is building the largest fleet of AI-enabled vehicles, the Optimus humanoid robot, and Dojo training infrastructure. Full Self-Driving plus humanoid robotics make TSLA the most diversified AI-physical-world bet. PNTHR holds TSLA as a top-tier AI Elite holding spanning autonomy and robotics.' },
      { ticker: 'ISRG', name: 'Intuitive Surgical', thesis: 'Intuitive Surgical owns the da Vinci surgical robot platform, AI-augmented robotic surgery is exploding. Massive installed base, recurring revenue, AI imaging upgrades. PNTHR holds ISRG as a top-tier AI medical robotics Elite name.' },
      { ticker: 'SYM', name: 'Symbotic Inc.', thesis: 'Symbotic builds AI-driven warehouse automation systems for Walmart and others. Pure-play warehouse AI robotics. PNTHR holds SYM as a focused AI warehouse robotics pure play.' },
      { ticker: 'SERV', name: 'Serve Robotics', thesis: 'Serve Robotics operates autonomous sidewalk delivery robots backed by NVIDIA and Uber. Pure-play autonomous last-mile robotics. PNTHR holds SERV as a small-cap robotics lottery ticket with NVIDIA partnership.' },
      { ticker: 'PATH', name: 'UiPath Inc.', thesis: 'UiPath is the leader in robotic process automation, AI-augmented enterprise workflow automation. PNTHR holds PATH as the software-RPA AI play.' },
      { ticker: 'ARBE', name: 'Arbe Robotics', thesis: 'Arbe Robotics designs 4D imaging radar for autonomous vehicles, the perception sensor enabling Level 4+ autonomy. PNTHR holds ARBE as a small-cap autonomous-perception pure play.' },
      { ticker: 'CGNX', name: 'Cognex Corporation', thesis: 'Cognex is the leader in machine vision, AI-augmented industrial inspection used by every major manufacturer and warehouse robotics deployment. PNTHR holds CGNX as a top-tier AI machine vision Elite holding.' },
      { ticker: 'AUR', name: 'Aurora Innovation', thesis: 'Aurora Innovation is the leading autonomous trucking pure-play, with NVIDIA partnership and commercial Texas freight launches. PNTHR holds AUR as the cornerstone autonomous trucking holding.' },
      { ticker: 'MBLY', name: 'Mobileye Global', thesis: 'Mobileye designs the AI vision systems and ADAS chips for major OEMs globally. Spun off from Intel, beaten down, AI-vehicle inflection ahead. PNTHR holds MBLY as a focused autonomous driving pure play.' },
      { ticker: 'OUST', name: 'Ouster Inc.', thesis: 'Ouster is the largest US LIDAR pure-play after the Velodyne merger, AI-driven 3D perception across robotics, autonomous vehicles, and security. PNTHR holds OUST as the leading LIDAR pure-play.' },
      { ticker: 'JOBY', name: 'Joby Aviation', thesis: 'Joby Aviation is the leading eVTOL (electric vertical takeoff and landing) pure-play, backed by Toyota, with FAA certification approaching. PNTHR holds JOBY as a top-tier autonomous aviation lottery ticket.' },
      { ticker: 'ACHR', name: 'Archer Aviation', thesis: 'Archer Aviation builds the Midnight eVTOL with United Airlines partnership, second-mover urban air mobility play. PNTHR holds ACHR as the second leg of our eVTOL exposure.' },
      { ticker: 'EH', name: 'EHang Holdings', thesis: 'EHang operates the only certified autonomous passenger aerial vehicle (in China). First-mover in actual commercial air-taxi operations. PNTHR holds EH as a unique autonomous-aviation pure play.' },
      { ticker: 'APTV', name: 'Aptiv PLC', thesis: 'Aptiv designs the connected car and ADAS platforms supplying every major OEM. AI vehicle intelligence runs through Aptiv. PNTHR holds APTV as a top-tier AI auto Tier 1 supplier.' },
      { ticker: 'MGA', name: 'Magna International', thesis: 'Magna manufactures EV powertrains, ADAS, and complete vehicles for major OEMs. AI-vehicle integration is core revenue. PNTHR holds MGA as a diversified AI auto supplier.' },
      { ticker: 'GNTX', name: 'Gentex Corporation', thesis: 'Gentex makes AI-enabled mirrors, cameras, and automotive electronics. AI-driven vehicle features drive content gains per car. PNTHR holds GNTX as a focused AI auto-electronics play.' },
      { ticker: 'AEVA', name: 'Aeva Technologies', thesis: 'Aeva builds 4D LIDAR with built-in velocity detection, uniquely positioned for autonomous trucking and rail. PNTHR holds AEVA as a small-cap differentiated LIDAR play.' },
      { ticker: 'INVZ', name: 'Innoviz Technologies', thesis: 'Innoviz designs solid-state LIDAR for autonomous vehicles with major OEM design wins. PNTHR holds INVZ as a small-cap LIDAR pure play.' },
      { ticker: 'LIDR', name: 'AEye Inc.', thesis: 'AEye builds adaptive LIDAR for autonomous vehicles and intelligent transportation systems. PNTHR holds LIDR as a micro-cap LIDAR optionality bet.' },
      { ticker: 'HSAI', name: 'Hesai Group', thesis: 'Hesai is the largest LIDAR producer globally, with dominant share in Chinese autonomous vehicles. PNTHR holds HSAI as a leading LIDAR pure-play with Chinese AV exposure.' },
      { ticker: 'ZBRA', name: 'Zebra Technologies', thesis: 'Zebra Technologies leads enterprise mobility, RFID, and machine-vision for AI-augmented warehouses, retail, and healthcare. PNTHR holds ZBRA as a top-tier industrial AI/IoT Elite holding.' },
      { ticker: 'PONY', name: 'Pony AI', thesis: 'Pony AI is a leading Chinese autonomous driving company recently US-listed, robotaxi and trucking deployments. PNTHR holds PONY as a Chinese autonomous-driving pure play.' },
      { ticker: 'WRD', name: 'WeRide Inc.', thesis: 'WeRide is a Chinese autonomous driving company recently US-listed with robobus, robotaxi, and Level 4 deployments. PNTHR holds WRD as the second leg of our Chinese autonomous-driving exposure.' },
      { ticker: 'NIO', name: 'NIO Inc.', thesis: 'NIO is a leading Chinese premium EV maker with NIO Pilot ADAS and battery-swap network. PNTHR holds NIO as a premium Chinese EV-AI play.' },
      { ticker: 'LI', name: 'Li Auto', thesis: 'Li Auto sells Chinese hybrid SUVs with AI-driven cabin and driving features, fastest-growing premium Chinese EV. PNTHR holds LI as a focused Chinese EV-AI bet.' },
      { ticker: 'XPEV', name: 'XPeng Inc.', thesis: 'XPeng builds Chinese EVs with leading XNGP autonomous driving capabilities and humanoid-robot ambitions. PNTHR holds XPEV as a focused Chinese AI-EV play.' },
    ],
  },
  {
    id: 6,
    name: 'AI Hyperscalers & Mega-Cap Software',
    weight: 2,
    thesis: 'The hyperscalers are the demand pull of the entire AI economy, they buy the chips, build the data centers, sign the power deals, and operate the foundational AI services. PNTHR holds them at deliberately reduced weight: their AI exposure is real, but they are already over-owned in every benchmark and represent rotation risk in a concentrated AI fund.',
    holdings: [
      { ticker: 'MSFT', name: 'Microsoft Corporation', thesis: 'Microsoft is the leading enterprise AI provider with Azure OpenAI, Copilot across the entire product suite, and direct OpenAI partnership. They are the AI-monetization mega-cap. PNTHR holds MSFT as a foundational AI Elite name with intentionally capped weight.' },
      { ticker: 'GOOGL', name: 'Alphabet Inc.', thesis: 'Alphabet runs Google Cloud TPU, Gemini foundation models, Waymo autonomous driving, and DeepMind. The most vertically-integrated AI company on Earth. PNTHR holds GOOGL with capped weight, owning the franchise without over-concentration.' },
      { ticker: 'META', name: 'Meta Platforms', thesis: 'Meta operates Llama open-weight foundation models, the largest GPU training cluster outside hyperscalers, and AI-augmented advertising at unmatched scale. PNTHR holds META as a foundational AI Elite name.' },
      { ticker: 'AMZN', name: 'Amazon.com Inc.', thesis: 'Amazon Web Services dominates cloud infrastructure, runs Bedrock plus Trainium custom AI silicon, and integrates AI across retail and logistics. PNTHR holds AMZN as a cornerstone AI mega-cap with capped weight.' },
      { ticker: 'ORCL', name: 'Oracle Corporation', thesis: 'Oracle Cloud Infrastructure is the surprise AI cloud winner, direct OpenAI deal, NVIDIA partnership, and the highest AI-revenue growth among legacy enterprise software. PNTHR holds ORCL as the re-rating mega-cap AI play.' },
      { ticker: 'IBM', name: 'IBM Corporation', thesis: 'IBM offers watsonx AI platform plus quantum computing leadership. Enterprise AI plus quantum optionality. PNTHR holds IBM as a diversified mega-cap AI play with quantum upside.' },
    ],
  },
  {
    id: 7,
    name: 'AI Software & Agentic Platforms',
    weight: 5,
    thesis: 'Where AI meets enterprise revenue. From Palantir\'s government AI dominance to Salesforce\'s Agentforce platform to ServiceNow\'s AI-native workflows, this sector captures the application-layer AI software companies monetizing the model layer. PNTHR holds the durable software franchises with the cleanest AI inflections.',
    holdings: [
      { ticker: 'PLTR', name: 'Palantir Technologies', thesis: 'Palantir runs the AIP (AI Platform) for government, defense, and enterprise, the leading commercial AI deployment platform with massive Department of Defense exposure. PNTHR holds PLTR as a top-tier AI Elite software holding.' },
      { ticker: 'SNOW', name: 'Snowflake Inc.', thesis: 'Snowflake is the AI data cloud, the storage and compute layer where enterprise AI training data lives. PNTHR holds SNOW as a foundational AI data infrastructure play.' },
      { ticker: 'MDB', name: 'MongoDB Inc.', thesis: 'MongoDB is the leading document database for AI applications, with Atlas Vector Search powering RAG (retrieval-augmented generation) workloads. PNTHR holds MDB as a focused AI database pure play.' },
      { ticker: 'DDOG', name: 'Datadog Inc.', thesis: 'Datadog is the leader in cloud observability, increasingly extending into AI/LLM monitoring. AI deployments need Datadog. PNTHR holds DDOG as the cloud-AI observability Elite holding.' },
      { ticker: 'APP', name: 'AppLovin Corp', thesis: 'AppLovin runs AI-driven mobile ad targeting at unmatched scale, pure-play AI-monetized advertising. Massive ROI for advertisers, structural AI tailwind. PNTHR holds APP as a top-tier AI advertising platform.' },
      { ticker: 'DUOL', name: 'Duolingo Inc.', thesis: 'Duolingo embeds AI tutoring and personalized language learning at scale, with explicit AI-driven feature rollouts. PNTHR holds DUOL as a consumer AI subscription pure play.' },
      { ticker: 'CRM', name: 'Salesforce Inc.', thesis: 'Salesforce launched Agentforce, the leading enterprise AI-agent platform monetizing Customer 360 data with autonomous agents. PNTHR holds CRM as a top-tier AI agent platform play.' },
      { ticker: 'NOW', name: 'ServiceNow Inc.', thesis: 'ServiceNow integrates Now Assist AI across IT, HR, and customer workflows, best-in-class AI monetization on enterprise SaaS. PNTHR holds NOW as a foundational AI workflow Elite holding.' },
      { ticker: 'ADBE', name: 'Adobe Inc.', thesis: 'Adobe owns Firefly generative AI for creative workflows and AI Acrobat for document intelligence. Massive installed base, AI-native feature inflection. PNTHR holds ADBE as a re-rating AI creative play.' },
      { ticker: 'GTLB', name: 'GitLab Inc.', thesis: 'GitLab launched Duo AI, AI-augmented DevSecOps for the full software lifecycle. PNTHR holds GTLB as a focused AI dev-tools play.' },
      { ticker: 'ESTC', name: 'Elastic NV', thesis: 'Elastic is the leading search-AI platform, vector search and RAG infrastructure for enterprise AI. PNTHR holds ESTC as a focused AI search and observability play.' },
      { ticker: 'PEGA', name: 'Pegasystems', thesis: 'Pegasystems delivers AI-driven workflow automation and decisioning for enterprise. PNTHR holds PEGA as a focused enterprise-AI-decisioning play.' },
      { ticker: 'MNDY', name: 'Monday.com Ltd', thesis: 'Monday.com integrates AI across work management with Monday AI features. PNTHR holds MNDY as a focused AI work management play.' },
      { ticker: 'INTU', name: 'Intuit Inc.', thesis: 'Intuit embeds AI in TurboTax, QuickBooks, and Credit Karma, consumer AI fintech at massive scale. PNTHR holds INTU as a quality consumer-AI compounder.' },
      { ticker: 'WDAY', name: 'Workday Inc.', thesis: 'Workday integrates AI across HR and finance enterprise SaaS. PNTHR holds WDAY as the enterprise HR/finance AI play.' },
      { ticker: 'DT', name: 'Dynatrace Inc.', thesis: 'Dynatrace delivers AIOps observability, automatic AI-driven application monitoring at enterprise scale. PNTHR holds DT as a focused AIOps pure play.' },
      { ticker: 'DOCN', name: 'DigitalOcean Holdings', thesis: 'DigitalOcean serves SMB cloud infrastructure with growing AI compute exposure through Paperspace acquisition. PNTHR holds DOCN as an SMB-focused AI cloud play.' },
      { ticker: 'HUBS', name: 'HubSpot Inc.', thesis: 'HubSpot integrates AI across marketing, sales, and service software for SMB. PNTHR holds HUBS as a focused SMB AI software play.' },
      { ticker: 'BSY', name: 'Bentley Systems', thesis: 'Bentley Systems provides AI-augmented infrastructure design software for engineers, digital twins for AI-driven infrastructure. PNTHR holds BSY as a focused engineering-AI pure play.' },
      { ticker: 'PTC', name: 'PTC Inc.', thesis: 'PTC provides AI-augmented industrial software (CAD, PLM, IoT). PNTHR holds PTC as a focused industrial-AI software play.' },
      { ticker: 'ROP', name: 'Roper Technologies', thesis: 'Roper Technologies operates a portfolio of vertical AI software businesses, diversified, recurring, AI-monetizing. PNTHR holds ROP as a diversified AI software conglomerate.' },
      { ticker: 'FICO', name: 'Fair Isaac Corp', thesis: 'FICO delivers AI-driven credit scoring and decisioning analytics, irreplaceable AI-fintech infrastructure. PNTHR holds FICO as a deep-moat AI analytics Elite holding.' },
      { ticker: 'VRSK', name: 'Verisk Analytics', thesis: 'Verisk provides AI-augmented analytics for insurance and energy, proprietary data plus AI insights. PNTHR holds VRSK as a focused AI-data-analytics play.' },
      { ticker: 'MANH', name: 'Manhattan Associates', thesis: 'Manhattan Associates leads AI-driven supply chain software for retail and commerce. PNTHR holds MANH as a focused AI supply chain pure play.' },
      { ticker: 'VEEV', name: 'Veeva Systems', thesis: 'Veeva provides AI-augmented life sciences cloud software, pharmaceutical and biotech AI workflow infrastructure. PNTHR holds VEEV as a focused vertical AI SaaS play.' },
      { ticker: 'U', name: 'Unity Software', thesis: 'Unity runs the leading 3D content engine plus AI-driven mobile ad-tech. AI 3D content generation tailwind. PNTHR holds U as a focused AI 3D engine play.' },
      { ticker: 'RBLX', name: 'Roblox Corporation', thesis: 'Roblox is the leading user-generated 3D platform with AI-driven content creation tools and AI moderation. PNTHR holds RBLX as a consumer AI 3D platform play.' },
      { ticker: 'TTWO', name: 'Take-Two Interactive', thesis: 'Take-Two integrates AI across game development with Rockstar and 2K studios. AI-driven NPCs, content, and procedural generation. PNTHR holds TTWO as a premium AI gaming play.' },
      { ticker: 'EA', name: 'Electronic Arts', thesis: 'Electronic Arts integrates AI across sports games, FPS, and Battlefield franchises. PNTHR holds EA as a diversified AI gaming play.' },
      { ticker: 'TYL', name: 'Tyler Technologies', thesis: 'Tyler Technologies is the leading government software vendor, increasingly integrating AI for civic workflows. PNTHR holds TYL as a focused government-AI software play.' },
      { ticker: 'PINS', name: 'Pinterest Inc.', thesis: 'Pinterest operates AI-driven visual search and discovery, billions of pins, AI-powered recommendations. PNTHR holds PINS as a focused consumer AI-discovery play.' },
      { ticker: 'ALRM', name: 'Alarm.com Holdings', thesis: 'Alarm.com delivers AI-powered home and business security plus IoT platform. Edge AI for residential and SMB. PNTHR holds ALRM as a focused IoT-AI security play.' },
      { ticker: 'SOUN', name: 'SoundHound AI', thesis: 'SoundHound AI is the voice AI pure-play with disclosed NVIDIA stake, automotive voice AI and enterprise conversational AI. PNTHR holds SOUN as a high-beta voice-AI lottery ticket.' },
      { ticker: 'CDW', name: 'CDW Corporation', thesis: 'CDW is the leading IT distribution channel for AI servers and infrastructure to enterprise. AI hardware buildout flows through CDW\'s warehouses. PNTHR holds CDW as the AI IT distribution and channel pure play.' },
    ],
  },
  {
    id: 8,
    name: 'AI Cybersecurity',
    weight: 3,
    thesis: 'AI is creating the largest attack surface in computing history, agents, models, data pipelines, all vulnerable. AI also empowers attackers with new capabilities. PNTHR holds the cybersecurity leaders monetizing both the AI defense buildout and the AI-augmented detection arms race.',
    holdings: [
      { ticker: 'PANW', name: 'Palo Alto Networks', thesis: 'Palo Alto Networks is the leading cybersecurity platform with AI-driven XSIAM, Cortex, and Prisma Cloud. AI-augmented security across the kill chain. PNTHR holds PANW as a top-tier AI cyber Elite holding.' },
      { ticker: 'CRWD', name: 'CrowdStrike Holdings', thesis: 'CrowdStrike leads in AI-driven endpoint detection and response, Charlotte AI agent plus Falcon platform. PNTHR holds CRWD as a foundational AI-endpoint security holding.' },
      { ticker: 'ZS', name: 'Zscaler Inc.', thesis: 'Zscaler operates the leading zero-trust cloud security platform with AI-augmented threat detection. PNTHR holds ZS as a focused zero-trust AI cloud security play.' },
      { ticker: 'FTNT', name: 'Fortinet Inc.', thesis: 'Fortinet delivers AI-augmented network security plus FortiGuard threat intelligence. PNTHR holds FTNT as a quality cyber compounder with AI inflection.' },
      { ticker: 'S', name: 'SentinelOne Inc.', thesis: 'SentinelOne provides AI-native endpoint protection, autonomous threat detection and response. PNTHR holds S as a focused AI-endpoint pure play.' },
      { ticker: 'RBRK', name: 'Rubrik Inc.', thesis: 'Rubrik delivers AI-driven data security and recovery, protecting AI training data and enterprise backups. Recently public with strong growth. PNTHR holds RBRK as a focused AI-data-security play.' },
      { ticker: 'OKTA', name: 'Okta Inc.', thesis: 'Okta is the leading identity-as-a-service platform, AI-driven authentication and access management. AI agents need identity. PNTHR holds OKTA as the identity-AI cornerstone.' },
      { ticker: 'VRNS', name: 'Varonis Systems', thesis: 'Varonis provides AI-driven data security and access governance. PNTHR holds VRNS as a focused AI-data-governance play.' },
      { ticker: 'TENB', name: 'Tenable Holdings', thesis: 'Tenable leads in AI-augmented vulnerability management and exposure management. PNTHR holds TENB as a focused vulnerability-management AI play.' },
      { ticker: 'RPD', name: 'Rapid7 Inc.', thesis: 'Rapid7 delivers AI-augmented security operations and threat detection. PNTHR holds RPD as a focused security-operations AI play.' },
      { ticker: 'QLYS', name: 'Qualys Inc.', thesis: 'Qualys provides cloud-native AI-augmented vulnerability and compliance management. PNTHR holds QLYS as a focused cloud-security AI play.' },
    ],
  },
  {
    id: 9,
    name: 'AI Ad-Tech, Marketing & Data Licensing',
    weight: 1,
    thesis: 'Programmatic advertising and AI training data are two sides of the same coin, both monetize attention and data with AI at the center. PNTHR holds a small, focused position in the AI-ad-tech leaders, knowing the trade is ROI-sensitive but the AI tailwind is real.',
    holdings: [
      { ticker: 'TTD', name: 'The Trade Desk', thesis: 'The Trade Desk is the leading independent demand-side ad platform, AI-driven programmatic advertising with Kokai AI agent. PNTHR holds TTD as the cornerstone AI-ad-tech Elite holding.' },
      { ticker: 'RDDT', name: 'Reddit Inc.', thesis: 'Reddit licenses its training data to OpenAI and Google, pure-play AI data licensing plus AI-driven advertising. Recently public, AI-native data play. PNTHR holds RDDT as a unique AI training data licensing pure play.' },
      { ticker: 'DV', name: 'DoubleVerify Holdings', thesis: 'DoubleVerify delivers AI-driven ad verification and brand safety. PNTHR holds DV as a focused ad-verification AI play.' },
      { ticker: 'MGNI', name: 'Magnite Inc.', thesis: 'Magnite is the largest independent sell-side ad platform, AI-driven CTV and programmatic advertising. PNTHR holds MGNI as a focused supply-side ad-tech AI play.' },
      { ticker: 'PUBM', name: 'PubMatic Inc.', thesis: 'PubMatic operates an AI-driven sell-side ad platform with strong CTV growth. PNTHR holds PUBM as a small-cap sell-side ad-tech AI play.' },
      { ticker: 'CRTO', name: 'Criteo SA', thesis: 'Criteo provides AI-driven retail media and performance advertising. PNTHR holds CRTO as a focused retail-media AI play.' },
    ],
  },
  {
    id: 10,
    name: 'AI Fintech',
    weight: 0.5,
    thesis: 'AI underwriting, AI insurance, AI lending, the financial services renovation is just beginning. PNTHR holds a small RADAR position in the pure-play AI fintech names: not because the thesis is broken, but because capital is currently elsewhere. Small starter positions ensure we are positioned when flow returns.',
    holdings: [
      { ticker: 'UPST', name: 'Upstart Holdings', thesis: 'Upstart operates AI-driven consumer lending, the original pure-play AI lender. Currently rate-sensitive but AI underwriting thesis intact. PNTHR holds UPST as a small RADAR position in pure-play AI lending.' },
      { ticker: 'LMND', name: 'Lemonade Inc.', thesis: 'Lemonade delivers AI-native insurance with AI claims processing and underwriting. PNTHR holds LMND as a small RADAR position in pure-play AI insurance.' },
      { ticker: 'AFRM', name: 'Affirm Holdings', thesis: 'Affirm operates AI-driven buy-now-pay-later underwriting. PNTHR holds AFRM as a focused AI BNPL play.' },
      { ticker: 'SOFI', name: 'SoFi Technologies', thesis: 'SoFi provides AI-augmented digital banking and lending platform. PNTHR holds SOFI as a diversified AI fintech play.' },
      { ticker: 'HOOD', name: 'Robinhood Markets', thesis: 'Robinhood operates a retail trading platform with AI-driven features and crypto. PNTHR holds HOOD as a focused retail-AI fintech play.' },
      { ticker: 'BILL', name: 'BILL Holdings', thesis: 'BILL delivers AI-augmented SMB financial operations, AP, AR, spend management. PNTHR holds BILL as a focused SMB AI fintech play.' },
    ],
  },
  {
    id: 11,
    name: 'AI Vertical SaaS & Workflow',
    weight: 0.5,
    thesis: 'Every vertical SaaS company is becoming an AI company, communications, contracts, real estate, restaurants. PNTHR holds a small RADAR position covering vertical SaaS AI exposure, ready to scale up when flow rotates here.',
    holdings: [
      { ticker: 'TWLO', name: 'Twilio Inc.', thesis: 'Twilio delivers AI-driven communications APIs and customer engagement platform. PNTHR holds TWLO as a focused communications-AI play.' },
      { ticker: 'ZM', name: 'Zoom Video Communications', thesis: 'Zoom integrates Zoom AI Companion across meetings, phone, and contact center. PNTHR holds ZM as a focused video-AI play.' },
      { ticker: 'DOCU', name: 'DocuSign Inc.', thesis: 'DocuSign is integrating AI across contract lifecycle management and agreement intelligence. PNTHR holds DOCU as a focused contracts-AI play.' },
      { ticker: 'DBX', name: 'Dropbox Inc.', thesis: 'Dropbox integrates Dash AI for universal search and content intelligence. PNTHR holds DBX as a focused cloud-storage-AI play.' },
      { ticker: 'BOX', name: 'Box Inc.', thesis: 'Box delivers Box AI for enterprise content intelligence and workflow. PNTHR holds BOX as a focused enterprise-content-AI play.' },
      { ticker: 'WIX', name: 'Wix.com Ltd', thesis: 'Wix integrates AI website builder and content generation. PNTHR holds WIX as a focused web-AI play.' },
      { ticker: 'GLBE', name: 'Global-E Online', thesis: 'Global-E delivers AI-driven cross-border ecommerce optimization. PNTHR holds GLBE as a focused ecommerce-AI play.' },
      { ticker: 'TOST', name: 'Toast Inc.', thesis: 'Toast provides AI-augmented restaurant operations platform. PNTHR holds TOST as a focused restaurant-AI play.' },
      { ticker: 'Z', name: 'Zillow Group', thesis: 'Zillow uses AI for home valuations and personalized real estate search. PNTHR holds Z as a focused real-estate AI play.' },
      { ticker: 'OPEN', name: 'Opendoor Technologies', thesis: 'Opendoor operates AI-driven iBuying and home transactions. PNTHR holds OPEN as a small-cap real-estate AI optionality bet.' },
      { ticker: 'CSGP', name: 'CoStar Group', thesis: 'CoStar Group delivers AI-augmented commercial real estate data and analytics. PNTHR holds CSGP as a focused commercial-real-estate AI data play.' },
    ],
  },
  {
    id: 12,
    name: 'AI Healthcare, Genomics & Drug Discovery',
    weight: 5,
    thesis: 'AI is rewriting drug discovery, diagnostics, and personalized medicine. NVIDIA-backed Tempus, Recursion, and Schrödinger are building the AI-pharma infrastructure of the future. PNTHR captures the pure-play AI biotech leaders plus the genomics tools companies that will be irreplaceable in AI-driven medicine.',
    holdings: [
      { ticker: 'TEM', name: 'Tempus AI', thesis: 'Tempus AI is NVIDIA-backed AI healthcare data platform, clinical-genomic AI for personalized medicine and drug discovery. Recently public, explosive growth. PNTHR holds TEM as the cornerstone AI healthcare Elite holding.' },
      { ticker: 'RXRX', name: 'Recursion Pharmaceuticals', thesis: 'Recursion uses AI to accelerate drug discovery, NVIDIA partnership and proprietary phenomics platform. PNTHR holds RXRX as a focused AI-drug-discovery pure play.' },
      { ticker: 'SDGR', name: 'Schrödinger Inc.', thesis: 'Schrödinger provides AI-driven physics-based drug discovery software plus internal pipeline. PNTHR holds SDGR as a focused AI-drug-discovery software play.' },
      { ticker: 'ABCL', name: 'AbCellera Biologics', thesis: 'AbCellera applies AI to antibody discovery, partnership-driven AI biotech. PNTHR holds ABCL as a focused AI antibody-discovery play.' },
      { ticker: 'ILMN', name: 'Illumina Inc.', thesis: 'Illumina is the leading DNA sequencing platform, AI-augmented sequencing analytics, foundational to AI biotech. PNTHR holds ILMN as a top-tier AI genomics Elite holding.' },
      { ticker: 'PACB', name: 'Pacific Biosciences', thesis: 'PacBio leads in long-read DNA sequencing, increasingly important for AI genomics applications. PNTHR holds PACB as a focused long-read sequencing AI play.' },
      { ticker: 'TWST', name: 'Twist Bioscience', thesis: 'Twist provides synthetic DNA and antibody libraries, the building blocks for AI-driven biology. PNTHR holds TWST as a focused AI-biology infrastructure play.' },
      { ticker: 'GH', name: 'Guardant Health', thesis: 'Guardant Health uses AI for liquid-biopsy cancer detection. PNTHR holds GH as a focused AI cancer-diagnostics play.' },
      { ticker: 'NTLA', name: 'Intellia Therapeutics', thesis: 'Intellia uses CRISPR plus AI for in vivo gene editing therapeutics. PNTHR holds NTLA as a focused gene-editing AI biotech.' },
      { ticker: 'NTRA', name: 'Natera Inc.', thesis: 'Natera applies AI to genetic testing, prenatal, transplant, and oncology. PNTHR holds NTRA as a focused AI genetic-testing play.' },
      { ticker: 'TXG', name: '10x Genomics', thesis: '10x Genomics provides AI-augmented single-cell sequencing platforms. PNTHR holds TXG as a focused single-cell AI play.' },
      { ticker: 'ARCT', name: 'Arcturus Therapeutics', thesis: 'Arcturus develops mRNA therapeutics with AI-augmented design. PNTHR holds ARCT as a focused mRNA-AI biotech.' },
      { ticker: 'MASS', name: '908 Devices', thesis: '908 Devices builds AI-augmented mass spectrometry analytical instruments. PNTHR holds MASS as a small-cap AI analytics device play.' },
      { ticker: 'NRIX', name: 'Nurix Therapeutics', thesis: 'Nurix uses AI for targeted protein degradation drug discovery. PNTHR holds NRIX as a focused AI-drug-discovery biotech.' },
    ],
  },
  {
    id: 13,
    name: 'Drones, Space & Defense AI',
    weight: 7,
    thesis: 'The Pentagon and allies are spending unprecedented capital on AI-powered drones, autonomous systems, satellite intelligence, and AI-augmented defense software. PNTHR\'s defense-AI sector captures the prime contractors, drone pure-plays, space companies, and government services firms profiting from the AI defense super-cycle.',
    holdings: [
      { ticker: 'RKLB', name: 'Rocket Lab USA', thesis: 'Rocket Lab is the leading small-satellite launch and space systems company, exploding backlog from AI-data satellite constellations. PNTHR holds RKLB as a top-tier space-AI Elite holding.' },
      { ticker: 'ASTS', name: 'AST SpaceMobile', thesis: 'AST SpaceMobile builds the only direct-to-cell satellite broadband network, AI-driven space-based connectivity. PNTHR holds ASTS as a high-conviction space-AI lottery ticket.' },
      { ticker: 'PL', name: 'Planet Labs', thesis: 'Planet Labs operates the largest commercial Earth-observation satellite constellation, AI-driven geospatial intelligence for governments and enterprises. PNTHR holds PL as the cornerstone AI-geospatial pure play.' },
      { ticker: 'LUNR', name: 'Intuitive Machines', thesis: 'Intuitive Machines is the leading lunar lander and space services company, AI-augmented space exploration with NASA contracts. PNTHR holds LUNR as a focused lunar-AI play.' },
      { ticker: 'RDW', name: 'Redwire Corporation', thesis: 'Redwire builds AI-augmented in-space manufacturing and space infrastructure. PNTHR holds RDW as a focused space-infrastructure AI play.' },
      { ticker: 'SATS', name: 'EchoStar Corporation', thesis: 'EchoStar/SATS operates satellite communications and 5G spectrum, AI-augmented connectivity. PNTHR holds SATS as a focused satellite-comms AI play.' },
      { ticker: 'AVAV', name: 'AeroVironment Inc.', thesis: 'AeroVironment builds the Switchblade loitering munitions and Puma drones, AI-augmented military drones with massive Department of Defense exposure. PNTHR holds AVAV as a top-tier military drone Elite holding.' },
      { ticker: 'ONDS', name: 'Ondas Holdings', thesis: 'Ondas Holdings operates American Robotics autonomous drones and rail networking. PNTHR holds ONDS as a small-cap drone-AI play.' },
      { ticker: 'HON', name: 'Honeywell International', thesis: 'Honeywell operates Quantinuum (quantum), avionics, and industrial AI businesses. Diversified AI exposure with quantum optionality. PNTHR holds HON as a quality industrial AI conglomerate.' },
      { ticker: 'OSK', name: 'Oshkosh Corporation', thesis: 'Oshkosh builds tactical military vehicles and AI-augmented logistics, Department of Defense contracts. PNTHR holds OSK as a focused defense vehicles play.' },
      { ticker: 'BAH', name: 'Booz Allen Hamilton', thesis: 'Booz Allen Hamilton is a leading government AI services firm with deep Department of Defense and intelligence community AI contracts. PNTHR holds BAH as a top-tier government-AI services Elite holding.' },
      { ticker: 'KTOS', name: 'Kratos Defense & Security', thesis: 'Kratos builds the Valkyrie autonomous fighter wingman, pure-play AI military drones. Department of Defense AI program centerpiece. PNTHR holds KTOS as a high-conviction AI defense drone Elite holding.' },
      { ticker: 'LDOS', name: 'Leidos Holdings', thesis: 'Leidos provides AI-driven services to defense, intelligence, and civil government. PNTHR holds LDOS as a focused government-AI services play.' },
      { ticker: 'TRMB', name: 'Trimble Inc.', thesis: 'Trimble delivers AI-augmented geospatial, agriculture, and construction technology. PNTHR holds TRMB as a focused geospatial-AI Elite holding.' },
      { ticker: 'MRCY', name: 'Mercury Systems', thesis: 'Mercury Systems builds AI-augmented mission electronics for defense and aerospace. PNTHR holds MRCY as a focused defense-electronics AI play.' },
      { ticker: 'IRDM', name: 'Iridium Communications', thesis: 'Iridium operates the only truly global satellite communications constellation, AI-augmented connectivity. PNTHR holds IRDM as a focused satellite-comms play.' },
      { ticker: 'LMT', name: 'Lockheed Martin', thesis: 'Lockheed Martin is the largest US defense prime, AI-augmented platforms across Aeronautics, Missiles, and Space. PNTHR holds LMT as a quality defense AI compounder.' },
      { ticker: 'RTX', name: 'RTX Corporation', thesis: 'RTX (Raytheon plus Pratt & Whitney plus Collins) operates AI-augmented missiles, radars, and aerospace. PNTHR holds RTX as a diversified defense AI prime.' },
      { ticker: 'NOC', name: 'Northrop Grumman', thesis: 'Northrop Grumman builds AI-augmented stealth aircraft (B-21), space systems, and missile defense. PNTHR holds NOC as a focused defense-AI prime.' },
      { ticker: 'GD', name: 'General Dynamics', thesis: 'General Dynamics operates AI-augmented IT services (GDIT) and combat systems. PNTHR holds GD as a diversified defense AI play.' },
      { ticker: 'SAIC', name: 'Science Applications International', thesis: 'SAIC delivers AI-driven government IT and defense services. PNTHR holds SAIC as a focused government-AI services play.' },
      { ticker: 'CACI', name: 'CACI International', thesis: 'CACI provides AI-augmented intelligence and defense services. PNTHR holds CACI as a focused intelligence-AI services play.' },
      { ticker: 'PSN', name: 'Parsons Corporation', thesis: 'Parsons delivers AI-driven defense, intelligence, and infrastructure services. PNTHR holds PSN as a focused government-AI infrastructure play.' },
      { ticker: 'RCAT', name: 'Red Cat Holdings', thesis: 'Red Cat builds Teal drones for US military, AI-augmented short-range reconnaissance UAS. PNTHR holds RCAT as a small-cap military-drone pure play.' },
      { ticker: 'DPRO', name: 'Draganfly Inc.', thesis: 'Draganfly builds AI-augmented drones for defense, public safety, and agriculture. PNTHR holds DPRO as a small-cap drone optionality bet.' },
      { ticker: 'HEI', name: 'HEICO Corporation', thesis: 'HEICO supplies aftermarket aerospace and defense electronics, quality compounder with AI defense exposure. PNTHR holds HEI as a quality defense-electronics compounder.' },
      { ticker: 'TDG', name: 'TransDigm Group', thesis: 'TransDigm provides proprietary aerospace components, defense AI exposure through aircraft platforms. PNTHR holds TDG as a quality aerospace compounder.' },
      { ticker: 'CW', name: 'Curtiss-Wright', thesis: 'Curtiss-Wright builds defense electronics, naval nuclear, and aerospace, diversified AI defense exposure. PNTHR holds CW as a diversified defense AI play.' },
      { ticker: 'TXT', name: 'Textron Inc.', thesis: 'Textron operates Bell helicopters, Cessna, and AI-augmented defense platforms. PNTHR holds TXT as a diversified aerospace-defense AI play.' },
      { ticker: 'BBAI', name: 'BigBear.ai Holdings', thesis: 'BigBear.ai delivers AI-driven decision intelligence for defense and intelligence community. PNTHR holds BBAI as a small-cap defense-AI software lottery ticket.' },
      { ticker: 'HAWK', name: 'BlackHawk Growth Corp', thesis: 'HAWK operates AI-powered satellite intelligence and geospatial analytics for commercial and government customers. As AI-driven Earth observation and satellite data processing become critical for defense, agriculture, and climate monitoring, HAWK captures the intersection of space infrastructure and AI analytics. PNTHR holds HAWK as a focused AI satellite intelligence play.' },
    ],
  },
  {
    id: 14,
    name: 'International AI / EM ADRs',
    weight: 0.5,
    thesis: 'AI is global. Chinese hyperscalers, Latin American ecommerce platforms, Asian fintech, all are AI-monetizing at scale. PNTHR holds a small RADAR position in the international AI ADRs, accepting geopolitical risk in exchange for exposure to AI markets US benchmarks ignore.',
    holdings: [
      { ticker: 'BABA', name: 'Alibaba Group', thesis: 'Alibaba runs Qwen open-source LLMs, Alibaba Cloud AI infrastructure, and AI-driven ecommerce at Chinese scale. PNTHR holds BABA as a focused Chinese AI-cloud RADAR position.' },
      { ticker: 'BIDU', name: 'Baidu Inc.', thesis: 'Baidu operates Ernie LLM, AI-driven search, and Apollo autonomous driving platform. PNTHR holds BIDU as a focused Chinese AI-search RADAR position.' },
      { ticker: 'MELI', name: 'MercadoLibre', thesis: 'MercadoLibre is the dominant Latin American ecommerce and fintech platform, AI-driven ad and credit. PNTHR holds MELI as a focused LatAm AI compounder.' },
      { ticker: 'CPNG', name: 'Coupang Inc.', thesis: 'Coupang operates Korean ecommerce with AI-driven logistics and ad-tech. PNTHR holds CPNG as a focused Korean AI ecommerce play.' },
      { ticker: 'GRAB', name: 'Grab Holdings', thesis: 'Grab is the leading Southeast Asian super-app, AI-driven mobility, delivery, and fintech. PNTHR holds GRAB as a focused SE Asian AI super-app play.' },
      { ticker: 'NU', name: 'Nu Holdings', thesis: 'Nu Holdings operates Brazil\'s leading digital bank with AI-driven underwriting. PNTHR holds NU as a focused LatAm AI fintech play.' },
      { ticker: 'SE', name: 'Sea Limited', thesis: 'Sea Limited operates Shopee ecommerce, SeaMoney fintech, and Garena gaming with AI across all three. PNTHR holds SE as a focused SE Asian AI conglomerate.' },
    ],
  },
  {
    id: 15,
    name: 'Quantum Computing',
    weight: 2,
    thesis: 'Quantum is the next computing paradigm, and an existential complement to AI. PNTHR holds a focused quantum basket: not because the technology is mature, but because when capital flow accelerates here, it accelerates violently. Small positions in every credible name ensure participation.',
    holdings: [
      { ticker: 'IONQ', name: 'IonQ Inc.', thesis: 'IonQ is the leading trapped-ion quantum computing pure-play with cloud quantum access via AWS, Azure, and Google. PNTHR holds IONQ as the cornerstone quantum holding.' },
      { ticker: 'RGTI', name: 'Rigetti Computing', thesis: 'Rigetti operates superconducting quantum computers with US government and commercial deployments. PNTHR holds RGTI as a focused superconducting-quantum bet.' },
      { ticker: 'QBTS', name: 'D-Wave Quantum', thesis: 'D-Wave Quantum is the leader in quantum annealing, practical optimization quantum computing. PNTHR holds QBTS as a focused quantum-annealing play.' },
      { ticker: 'QUBT', name: 'Quantum Computing Inc.', thesis: 'Quantum Computing Inc. develops photonic quantum systems and quantum software. PNTHR holds QUBT as a small-cap quantum lottery ticket.' },
      { ticker: 'ARQQ', name: 'Arqit Quantum', thesis: 'Arqit Quantum builds quantum-secure encryption (QKD) for defense and enterprise. PNTHR holds ARQQ as a focused quantum-cryptography play.' },
      { ticker: 'LAES', name: 'SEALSQ Corp', thesis: 'SEALSQ provides post-quantum cryptography semiconductors. PNTHR holds LAES as a small-cap post-quantum-security pure play.' },
      { ticker: 'INFQ', name: 'Infinity Quantum Technology', thesis: 'Infinity Quantum Technology develops quantum sensing and computing hardware. PNTHR holds INFQ as a focused quantum-technology pure play.' },
    ],
  },
  {
    id: 16,
    name: 'AI Materials, Packaging, Thermal & Industrial',
    weight: 1.5,
    thesis: 'Advanced packaging is the AI manufacturing chokepoint. AI cooling is the AI data center bottleneck. AI rare earths and copper are the physical foundations of the AI economy. PNTHR captures the materials, packaging, thermal, and industrial pure-plays that make AI possible at the atomic and physical layer.',
    holdings: [
      { ticker: 'VRT', name: 'Vertiv Holdings', thesis: 'Vertiv is the leading AI data center thermal and power management vendor, liquid cooling for NVIDIA HGX systems. PNTHR holds VRT as a top-tier AI-cooling Elite holding.' },
      { ticker: 'TT', name: 'Trane Technologies', thesis: 'Trane Technologies provides HVAC and thermal management for AI data centers and industrial facilities. PNTHR holds TT as a quality compounder with explicit AI-cooling exposure.' },
      { ticker: 'JCI', name: 'Johnson Controls', thesis: 'Johnson Controls delivers AI data center cooling, fire safety, and building management. PNTHR holds JCI as a diversified AI infrastructure play.' },
      { ticker: 'AMKR', name: 'Amkor Technology', thesis: 'Amkor is the leading US-listed advanced packaging and OSAT vendor, CoWoS-adjacent packaging for AI chips. PNTHR holds AMKR as a focused advanced-packaging pure play.' },
      { ticker: 'ASX', name: 'ASE Technology Holding', thesis: 'ASE is the largest global OSAT, advanced packaging for AI chips at hyperscale. PNTHR holds ASX as a focused advanced-packaging Elite holding.' },
      { ticker: 'NVT', name: 'nVent Electric', thesis: 'nVent Electric provides electrical and liquid-cooling solutions for AI data centers. PNTHR holds NVT as a focused AI-cooling-and-electrical play.' },
      { ticker: 'ROK', name: 'Rockwell Automation', thesis: 'Rockwell Automation leads industrial AI automation, factory robots and AI manufacturing software. PNTHR holds ROK as a top-tier industrial-AI Elite holding.' },
      { ticker: 'EMR', name: 'Emerson Electric', thesis: 'Emerson Electric provides AI-augmented industrial automation plus AspenTech AI process modeling. PNTHR holds EMR as a diversified industrial AI play.' },
      { ticker: 'CARR', name: 'Carrier Global', thesis: 'Carrier Global delivers HVAC and refrigeration including AI data center cooling. PNTHR holds CARR as a focused HVAC AI play.' },
      { ticker: 'NNDM', name: 'Nano Dimension', thesis: 'Nano Dimension builds AI-augmented additive manufacturing systems. PNTHR holds NNDM as a small-cap AI 3D printing play.' },
      { ticker: 'MTLS', name: 'Materialise NV', thesis: 'Materialise provides AI-driven 3D printing software. PNTHR holds MTLS as a focused 3D printing software play.' },
      { ticker: 'SSYS', name: 'Stratasys Ltd', thesis: 'Stratasys is the leader in industrial 3D printing, AI-augmented additive manufacturing for aerospace and defense. PNTHR holds SSYS as a focused industrial 3D printing play.' },
      { ticker: 'DDD', name: '3D Systems Corporation', thesis: '3D Systems provides industrial and dental AI-augmented 3D printing. PNTHR holds DDD as a small-cap 3D printing optionality bet.' },
      { ticker: 'MP', name: 'MP Materials', thesis: 'MP Materials operates the only US rare earths mine and is building permanent magnet capacity, critical for AI data center motors, EVs, and defense. PNTHR holds MP as a strategic AI materials play.' },
      { ticker: 'ALB', name: 'Albemarle Corporation', thesis: 'Albemarle is the largest US-listed lithium producer, battery materials for AI grid storage and EVs. PNTHR holds ALB as a strategic AI battery materials play.' },
      { ticker: 'FCX', name: 'Freeport-McMoRan', thesis: 'Freeport-McMoRan is the largest US copper producer, AI data centers consume 6x more copper per square foot than traditional facilities. PNTHR holds FCX as a strategic AI-copper play.' },
      { ticker: 'FIX', name: 'Comfort Systems USA', thesis: 'Comfort Systems is a leading mechanical and HVAC contractor specializing in data center cooling infrastructure. Their modular cooling systems serve hyperscaler buildouts nationwide. PNTHR holds FIX as a focused HVAC contracting pure play on AI data center thermal management.' },
      { ticker: 'MOD', name: 'Modine Manufacturing', thesis: 'Modine manufactures precision thermal management solutions including liquid cooling systems purpose-built for AI data centers. Their data center cooling segment is the fastest-growing business line. PNTHR holds MOD as a focused thermal management pure play on AI compute cooling.' },
      { ticker: 'MLI', name: 'Mueller Industries', thesis: 'Mueller Industries is a leading copper and brass manufacturer supplying the tubing, fittings, and components critical to AI data center cooling and electrical systems. AI facilities consume multiples more copper than traditional buildings. PNTHR holds MLI as a strategic copper-products play on AI infrastructure buildout.' },
    ],
  },
];

// Verify total holdings count
export const TOTAL_HOLDINGS = SECTORS.reduce((sum, s) => sum + s.holdings.length, 0);
