"""Single source of truth for the PNTHR Tree investor performance numbers.

Generated by server/_tree_perfsummary_numbers.mjs (-> server/data/treeIr/_perf_summary.json)
from the LOCKED treeSim engine via irLiveService.computeSide -- the same numbers as the live
dashboard and the in-app Tree IR page. The Tree performance docs import T / SPY / ANNUAL from
here, so a baseline change flows through automatically (no manual number entry, no silent drift).

Regenerate after any baseline change:
    cd server/backtest && node --env-file=../.env genTreeIrData.js
    cd server        && node --env-file=.env _tree_perfsummary_numbers.mjs
    cd scripts       && python3 generate_tree_performance_summary.py   # + investor_explanation, ddq
"""
import json
import os

_PATH = os.path.normpath(os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "server", "data", "treeIr", "_perf_summary.json"))

with open(_PATH) as _f:
    PERF = json.load(_f)

T = PERF["tiers"]            # T['filet'|'porterhouse'|'wagyu']['gross'|'net'|'drag'|'trades'][...]
SPY = PERF["spy"]            # SPY['cagr'|'totalReturn'|'maxDD'|'sharpe'|'sortino'|'calmar'|'recovery']
ANNUAL = PERF["annual"]      # [{year,start,end,spy,tree,alpha}, ...]
PERIOD = PERF["backtestPeriod"]
